// Localized guidance for the signed but not yet notarized macOS release.
export const gatekeeperCopy = {
  en: ["macOS may show a verification warning. Read the download guidance before opening the file.", "If macOS can't verify the download", "Vunemi is signed, but this release has not yet been notarized by Apple. macOS may block the disk image. This warning does not prove the file is safe.", "Only continue if you downloaded this release from the link above and checked its SHA-256 against the value below.", "If you trust the file, choose Done in the warning. Open System Settings › Privacy & Security, scroll down and select Open Anyway. Confirm the next macOS prompt yourself. If unsure, do not open it; contact Support.", "Apple's instructions", "What to do if macOS blocks the download"],
  de: ["macOS kann eine Warnung zur Überprüfung anzeigen. Lies vor dem Öffnen die Hinweise zum Download.", "Wenn macOS den Download nicht überprüfen kann", "Vunemi ist signiert, aber diese Version wurde noch nicht von Apple notarisiert. macOS kann das Disk-Image blockieren. Die Warnung beweist nicht, dass die Datei sicher ist.", "Fahre nur fort, wenn du diese Version über den obigen Link geladen und ihren SHA-256-Wert mit dem unten angegebenen verglichen hast.", "Wenn du der Datei vertraust, wähle in der Warnung „Fertig“. Öffne Systemeinstellungen › Datenschutz & Sicherheit und wähle weiter unten „Dennoch öffnen“. Bestätige die nächste macOS-Meldung selbst. Wenn du unsicher bist, öffne die Datei nicht und kontaktiere die Hilfe.", "Anleitung von Apple", "Was tun, wenn macOS den Download blockiert?"],
  es: ["macOS puede mostrar un aviso de verificación. Lee las instrucciones antes de abrir el archivo.", "Si macOS no puede verificar la descarga", "Vunemi está firmado, pero Apple aún no ha notarizado esta versión. macOS puede bloquear la imagen de disco. El aviso no demuestra que el archivo sea seguro.", "Continúa solo si descargaste esta versión desde el enlace anterior y comprobaste que su SHA-256 coincide con el valor indicado abajo.", "Si confías en el archivo, pulsa «Aceptar» en el aviso. Abre Ajustes del Sistema › Privacidad y seguridad, baja hasta «Abrir igualmente» y confirma tú mismo el siguiente aviso de macOS. Si tienes dudas, no lo abras y contacta con Soporte.", "Instrucciones de Apple", "Qué hacer si macOS bloquea la descarga"],
  fr: ["macOS peut afficher un avertissement de vérification. Consultez les consignes avant d’ouvrir le fichier.", "Si macOS ne peut pas vérifier le téléchargement", "Vunemi est signé, mais cette version n’a pas encore été notarisée par Apple. macOS peut bloquer l’image disque. Cet avertissement ne prouve pas que le fichier est sûr.", "Ne poursuivez que si vous avez téléchargé cette version via le lien ci-dessus et comparé son SHA-256 à la valeur indiquée plus bas.", "Si vous faites confiance au fichier, choisissez « OK » dans l’alerte. Ouvrez Réglages Système › Confidentialité et sécurité, puis « Ouvrir quand même » en bas de page. Confirmez vous-même l’alerte suivante. En cas de doute, n’ouvrez pas le fichier et contactez l’assistance.", "Consignes d’Apple", "Que faire si macOS bloque le téléchargement ?"],
  it: ["macOS potrebbe mostrare un avviso di verifica. Leggi le indicazioni prima di aprire il file.", "Se macOS non riesce a verificare il download", "Vunemi è firmato, ma questa versione non è ancora stata autenticata da Apple. macOS potrebbe bloccare l’immagine disco. L’avviso non dimostra che il file sia sicuro.", "Procedi solo se hai scaricato questa versione dal link qui sopra e confrontato il suo SHA-256 con il valore riportato sotto.", "Se ti fidi del file, scegli «Fine» nell’avviso. Apri Impostazioni di Sistema › Privacy e sicurezza e seleziona «Apri comunque» in fondo alla pagina. Conferma personalmente il successivo avviso di macOS. Se hai dubbi, non aprirlo e contatta l’assistenza.", "Istruzioni di Apple", "Cosa fare se macOS blocca il download"],
  tr: ["macOS doğrulama uyarısı gösterebilir. Dosyayı açmadan önce indirme açıklamasını oku.", "macOS indirdiğin dosyayı doğrulayamadığını söylerse", "Vunemi imzalıdır, ancak bu sürüm henüz Apple tarafından noterlenmedi. Bu yüzden macOS disk görüntüsünü engelleyebilir. Bu uyarı, dosyanın güvenli olduğunun kanıtı değildir.", "Yalnızca bu sürümü yukarıdaki bağlantıdan indirdiysen ve SHA-256 değerinin aşağıdakiyle eşleştiğini doğruladıysan devam et.", "Dosyaya güveniyorsan uyarıda ‘Bitti’yi seç. Sistem Ayarları › Gizlilik ve Güvenlik bölümünün altındaki ‘Yine de Aç’ düğmesini seçip sonraki macOS onayını kendin ver. Emin değilsen dosyayı açma; Destek formundan bize yaz.", "Apple'ın yönergesi", "macOS indirmeyi engellerse ne yapmalı?"],
  pt: ["O macOS pode mostrar um aviso de verificação. Leia as orientações antes de abrir o arquivo.", "Se o macOS não conseguir verificar o download", "O Vunemi é assinado, mas esta versão ainda não foi notarizada pela Apple. O macOS pode bloquear a imagem de disco. O aviso não comprova que o arquivo é seguro.", "Prossiga somente se você baixou esta versão pelo link acima e conferiu o SHA-256 com o valor abaixo.", "Se confiar no arquivo, escolha «OK» no aviso. Abra Ajustes do Sistema › Privacidade e Segurança, role para baixo e selecione «Abrir Mesmo Assim». Confirme pessoalmente o próximo aviso do macOS. Se tiver dúvidas, não abra o arquivo; entre em contato pelo Suporte.", "Instruções da Apple", "O que fazer se o macOS bloquear o download"],
  ru: ["macOS может показать предупреждение о проверке. Перед открытием файла прочитайте инструкцию.", "Если macOS не может проверить загрузку", "Vunemi подписан, но эта версия ещё не прошла нотариальное заверение Apple. macOS может заблокировать образ диска. Предупреждение не доказывает, что файл безопасен.", "Продолжайте, только если загрузили эту версию по ссылке выше и сверили SHA-256 со значением ниже.", "Если доверяете файлу, нажмите «Готово» в предупреждении. Откройте Системные настройки › Конфиденциальность и безопасность, прокрутите вниз и выберите «Всё равно открыть». Подтвердите следующее окно macOS самостоятельно. Если сомневаетесь, не открывайте файл и свяжитесь с поддержкой.", "Инструкция Apple", "Что делать, если macOS блокирует загрузку"],
  zh: ["macOS 可能显示验证警告。打开文件前请先阅读下载说明。", "如果 macOS 提示无法验证下载文件", "Vunemi 已签名，但此版本尚未通过 Apple 公证。因此 macOS 可能阻止打开磁盘映像。此警告不代表文件已经被证明安全。", "只有在通过上方链接下载此版本，并核对其 SHA-256 与下方数值一致后，才继续操作。", "如果你信任该文件，请在警告中选择“完成”。打开“系统设置”›“隐私与安全性”，向下滚动并选择“仍要打开”。请自行确认随后的 macOS 提示。如果不确定，请不要打开文件，并通过支持页面联系我们。", "Apple 官方说明", "macOS 阻止打开下载文件时怎么办"],
  ja: ["macOS で検証に関する警告が表示される場合があります。ファイルを開く前に案内をご確認ください。", "macOS でダウンロードを検証できないと表示された場合", "Vunemi は署名されていますが、このバージョンはまだ Apple の公証を受けていません。そのため macOS がディスクイメージをブロックする場合があります。この警告はファイルの安全性を証明するものではありません。", "上のリンクからこのバージョンをダウンロードし、SHA-256 が下の値と一致することを確認した場合のみ続行してください。", "ファイルを信頼できる場合は警告で「完了」を選び、「システム設定」›「プライバシーとセキュリティ」を開いて下へスクロールし、「このまま開く」を選びます。次の macOS の確認にはご自身で対応してください。不安がある場合は開かずにサポートへご連絡ください。", "Apple の案内", "macOS がダウンロードをブロックした場合"],
  ko: ["macOS에서 확인 경고가 표시될 수 있습니다. 파일을 열기 전에 다운로드 안내를 읽어 주세요.", "macOS가 다운로드 파일을 확인할 수 없다고 할 때", "Vunemi는 서명되어 있지만 이 버전은 아직 Apple 공증을 받지 않았습니다. 따라서 macOS가 디스크 이미지를 차단할 수 있습니다. 이 경고가 파일의 안전성을 증명하는 것은 아닙니다.", "위 링크에서 이 버전을 다운로드했고 SHA-256 값이 아래 표시된 값과 일치하는지 확인한 경우에만 계속하세요.", "파일을 신뢰한다면 경고에서 ‘완료’를 선택하세요. 시스템 설정 › 개인정보 보호 및 보안으로 이동해 아래쪽의 ‘그래도 열기’를 선택하고 다음 macOS 확인은 직접 결정하세요. 확신이 없다면 파일을 열지 말고 지원 페이지로 문의하세요.", "Apple 안내", "macOS가 다운로드를 차단할 때"],
};
