export default {
  langName: "Deutsch",
  nav: { home: "Start", features: "Funktionen", screens: "Ansichten", download: "Herunterladen", guide: "Leitfaden" },
  language: "Sprache",
  skip: "Zum Inhalt springen",
  footer: "Diese Seite nutzt keine Cookies und keine Tracking-Skripte.",
  demo: {
      "user": "Finde die Rechnungen auf meinem Schreibtisch und leg sie in einen Ordner.",
      "planTitle": "Plan freigeben",
      "steps": [
          "Rechnungen auf dem Schreibtisch suchen",
          "Einen Ordner „Rechnungen“ anlegen",
          "Die Rechnungen hineinlegen"
      ],
      "go": "Los",
      "edit": "Bearbeiten",
      "cancel": "Abbrechen",
      "cardTitle": "4 Dateien verschieben",
      "cardBody": "Schreibtisch → Dokumente/Rechnungen",
      "approve": "Freigeben",
      "deny": "Ablehnen",
      "done": "Erledigt. Die 4 Rechnungen liegen in Dokumente/Rechnungen.",
      "logItem": "4 Dateien nach Rechnungen verschoben",
      "undo": "Rückgängig",
      "model": "Lokales Modell",
      "localNote": "Das KI-Modell läuft auf diesem Mac.",
      "noCloud": "Keine Verarbeitung in einer Vunemi-Cloud"
  },
  meta: {
    home: { title: "Vunemi: ein persönlicher Assistent, der auf deinem Mac läuft", description: "Vunemi hilft im Alltag. Die KI läuft auf deinem Mac, ohne Vunemi-Cloud-Konto. Du entscheidest, welche externen Dienste du verbindest." },
    features: { title: "Was Vunemi kann", description: "E-Mail, Kalender, Dateien, Web und deine Mac-Apps – mit Freigabekarten, Rückgängig und festen Grenzen. Alles, was Vunemi 0.1.18 kann." },
    screens: { title: "Vunemi-Ansichten", description: "Echte Ansichten der Vunemi-App für den Mac, mit Beispieldaten aufgenommen." },
    download: { title: "Vunemi für Mac herunterladen", description: "Lade Vunemi 0.1.18 für Macs mit Apple Silicon und macOS 14 oder neuer. Kostenlos und Open Source." },
  },
  hero: {
    eyebrow: "Persönlicher Assistent für den Mac",
    title: "Hilfe im Alltag. Die KI läuft auf deinem Mac.",
    lead: "Vunemi hilft bei E-Mails, Dateien, Kalender und Web. Es fragt, bevor es etwas ändert. Das KI-Modell läuft auf deinem Mac; Vunemi lädt Unterhaltungen und Dokumente nicht zur Verarbeitung in eine eigene Cloud hoch.",
    download: "Für Mac laden",
    explore: "Funktionen ansehen",
    facts: ["Kostenlos und Open Source", "Apple Silicon", "macOS 14 oder neuer"],
    caption: "Vunemi zeigt seinen Plan und wartet auf dich",
  },
  strengths: {
    title: "Was Vunemi anders macht",
    items: [
      { title: "Die KI läuft auf deinem Mac", body: "Kein Vunemi-Konto und kein Abo. Das KI-Modell verarbeitet Aufgaben auf deinem Mac. Wenn du Gmail, Outlook oder Websites verbindest, tauschen diese Dienste die für die Aufgabe nötigen Daten aus; sie sind keine Vunemi-Cloud-Dienste." },
      { title: "Du hast das letzte Wort", body: "Jede Verbindung ist anfangs aus. Bevor sich etwas ändert, zeigt Vunemi eine Karte, die genau sagt, was passieren wird, und wartet auf dich. Wie oft es fragt, bestimmst du." },
      { title: "Fehler lassen sich rückgängig machen", body: "Alles, was Vunemi tut, steht im Aktivitätsprotokoll mit einer Rückgängig-Taste. Gelöschte Dateien landen im Papierkorb, und eine gesendete E-Mail wartet 45 Sekunden, damit du sie zurückholen kannst." },
    ],
  },
  features: {
    title: "Wobei es hilft",
    intro: "Frag mit deinen eigenen Worten. Schalte nur die Verbindungen ein, die du brauchst.",
    more: "Alle Funktionen",
    cards: [
      { title: "E-Mails im Griff", body: "Findet Mails, die auf Antwort warten, fasst Verläufe zusammen und schreibt Entwürfe. Funktioniert mit den Accounts aus der Mail-App deines Mac, Gmail, Outlook und anderen IMAP-Konten und sendet nie ohne deine Freigabe.", example: "Welche E-Mails warten auf meine Antwort?" },
      { title: "Deinen Tag planen", body: "Liest deine Kalender und Erinnerungen, auch Google- oder Outlook-Kalender auf deinem Mac, und trägt Termine oder Aufgaben ein, wenn du zustimmst.", example: "Was steht morgen in meinem Kalender?" },
      { title: "Dateien finden und ordnen", body: "Durchsucht Schreibtisch, Dokumente und Downloads, liest Dokumente und verschiebt oder benennt Dateien nach deiner Freigabe um. Jede Änderung lässt sich rückgängig machen.", example: "Finde die Rechnungen auf meinem Schreibtisch und leg sie in einen Ordner." },
      { title: "Im Web nachschlagen", body: "Öffnet Seiten in einem Browser in Vunemi, getrennt von deinem eigenen. Es liest, vergleicht und füllt Formulare aus, und du kannst jederzeit auf „Übernehmen“ drücken.", example: "Vergleiche die Öffnungszeiten dieser drei Museen." },
      { title: "Deine Mac-Apps nutzen", body: "Arbeitet mit Notizen, Excel, Word, PowerPoint, Finder, Kontakte, Nachrichten und mehr, ohne auf dem Bildschirm herumzuklicken. Jede App hat ihren eigenen Schalter.", example: "Fass die Ausgaben in dieser Excel-Tabelle zusammen." },
      { title: "Sprechen statt tippen", body: "Diktiere mit einem Sprachmodell, das auf deinem Mac läuft: Du sprichst, deine Worte erscheinen als Text. Im Sprachchat liest Vunemi seine Antwort mit der Stimme deines Mac vor, und du kannst ihm ins Wort fallen.", example: "Zeig mir die heutigen Termine." },
      { title: "Aufgaben nach Plan", body: "Wünsch dir eine Morgenübersicht oder eine wöchentliche Prüfung. Geplante Aufgaben laufen, solange Vunemi geöffnet ist, und senden, löschen oder bezahlen nie.", example: "Fass jeden Morgen um 9 meinen Kalender zusammen." },
      { title: "Zeig ihm ein Bild", body: "Häng einen Screenshot oder ein Foto an. Modelle, die Bilder sehen können, beschreiben es; bei anderen liest Vunemi den Text darin trotzdem auf deinem Mac.", example: "Was bedeutet der Fehler in diesem Screenshot?" },
      { title: "Merkt sich, was du sagst", body: "Sag, wie du gern arbeitest oder wer wer ist, und Vunemi notiert es in deinen Worten, sobald du zustimmst. Jede Antwort zeigt, welche Notizen sie bekam; in den Einstellungen kannst du sie bearbeiten oder löschen.", example: "Merk dir: Berichte bitte als PDF." },
      { title: "Besprechung aufzeichnen", body: "Mit Aufnahme werden Mikrofon und Mac-Ton erfasst. Vunemi erstellt Transkript und Zusammenfassung auf diesem Mac; nach erfolgreicher Zusammenfassung wandert das Audio in den Papierkorb. Erfordert macOS 14.2 oder neuer.", example: "Diese Besprechung aufzeichnen." },
      { title: "Frühere Arbeit dazuholen", body: "Tippe @ und wähle eine frühere Sitzung oder eine Besprechung. Ihre Fragen und Antworten oder die Zusammenfassung der Besprechung gehen mit deiner Nachricht mit; bis zu fünf auf einmal.", example: "Welches Hotel haben wir in @Rom-Reise ausgewählt?" },
    ],
  },
  screens: {
    title: "So sieht es aus",
    intro: "Echte Ansichten der englischen App, mit Beispieldaten aufgenommen.",
    more: "Alle Ansichten",
    captions: {
      home: "Starte eine Aufgabe mit deinen eigenen Worten",
      plan: "Prüfe den Plan, bevor etwas passiert",
      browser: "Liest eine Webseite in seinem eigenen Browser und antwortet",
      mention: "Mit @ eine frühere Sitzung oder Besprechung in die Nachricht holen",
      permissions: "Bestimme, wann Vunemi vorher fragt",
      connections: "Jede Verbindung ist anfangs aus",
      scheduled: "Geplante Aufgaben, die nur lesen",
      vault: "Schlüssel bleiben im Tresor; das Modell sieht nur den Namen",
      model: "Wähle ein Modell, das zu deinem Mac passt",
    },
  },
  never: {
    title: "Was Vunemi nie tut",
    intro: "Auf jeder Berechtigungsstufe. An diesen Stellen hält es an und übergibt an dich.",
    items: ["Passwörter, Karten-, Bank- oder Ausweisnummern eingeben", "CAPTCHAs lösen", "Etwas bezahlen", "Etwas endgültig löschen"],
  },
  start: {
    title: "In drei Schritten loslegen",
    steps: [
      { title: "Laden und installieren", body: "Öffne das Disk-Image und zieh Vunemi in den Programme-Ordner." },
      { title: "Modell wählen", body: "Vunemi schlägt ein Modell vor, das zum Speicher deines Macs passt, und lädt es. Du nutzt schon LM Studio oder Ollama? Dann verbinde das." },
      { title: "Nur einschalten, was du brauchst", body: "Schalte unter Einstellungen › Verbindungen nur ein, was Vunemi nutzen soll." },
    ],
  },
  notes: {
    title: "Gut zu wissen",
    items: [
      "Die Ergebnisse hängen vom Modell und von deinem Mac ab. Ein kleines Modell macht bei komplexen Aufgaben mehr Fehler.",
      "Für Macs mit Apple Silicon und macOS 14 oder neuer.",
      "Aufgaben, auch geplante, laufen, solange Vunemi geöffnet ist.",
      "Die App ist signiert, aber noch nicht von Apple notarisiert. Beim ersten Start musst du eventuell unter Systemeinstellungen › Datenschutz & Sicherheit auf „Dennoch öffnen“ klicken.",
    ],
  },
  story: {
    eyebrow: "Warum Vunemi?",
    title: "Kleinigkeiten summieren sich.",
    body: "Eine E-Mail wartet auf Antwort, ein Dokument ist unauffindbar, der Kalender ist voll. Vunemi ist für solche Momente gemacht: Es übernimmt Kleinarbeit, fragt vor Aktionen und lässt die KI auf deinem Mac laufen.",
  },
  community: {
    title: "Open Source, gemeinsam entwickelt",
    body: "Der Code von Vunemi liegt unter der GPL-3.0-Lizenz auf GitHub. Alle können ihn lesen, prüfen, was er tut, und helfen, ihn besser zu machen.",
    link: "Vunemi auf GitHub",
  },
  featuresPage: {
    title: "Alles, was Vunemi kann",
    intro: "Vunemi 0.1.18 im Detail: wie du damit arbeitest, womit es sich verbinden kann und wie du die Kontrolle behältst.",
    chatTitle: "Mit Vunemi arbeiten",
    chat: [
      { title: "Erst der Plan", body: "Bei Aufgaben mit mehreren Schritten kann Vunemi zuerst den Plan zeigen. Leg los, bearbeite die Schritte oder brich ab." },
      { title: "Freigabekarten", body: "Jede Änderung kommt als Karte, die sagt, was passiert, wo und an wen." },
      { title: "Anstellen oder dazwischengehen", body: "Tipp die nächste Bitte, während eine Aufgabe läuft. Sie wartet, bis sie dran ist, oder du unterbrichst und lässt sie sofort erledigen." },
      { title: "Notstopp", body: "⌘⇧Esc stoppt eine laufende Aufgabe, auch wenn Vunemi gesperrt ist." },
      { title: "Macht dort weiter, wo es war", body: "Schließt sich Vunemi mitten in einer Aufgabe, sagt es dir, wie weit es gekommen ist, und bietet an weiterzumachen – mit Rückfrage vor jedem Schritt, der etwas ändert oder sendet." },
      { title: "Projekte", body: "Mach einen Ordner zum Projekt: Vunemi legt die Dateien dieser Arbeit dort ab, und jede Änderung lässt sich rückgängig machen." },
      { title: "Gedächtnis", body: "Notizen aus deinen eigenen Worten, gespeichert nur mit deiner Zustimmung. Eine Aufgabe bekommt nur die Notizen, die zu ihr passen, und die Antwort sagt, wie viele es waren." },
      { title: "Frühere Arbeit dazuholen", body: "Tippe @ und wähle eine frühere Sitzung oder eine Besprechung. Ihre Fragen und Antworten oder die Zusammenfassung der Besprechung gehen mit deiner Nachricht mit; bis zu fünf auf einmal." },
    ],
    connTitle: "Verbindungen",
    connIntro: "Jede Verbindung ist aus, bis du sie einschaltest. Eine ausgeschaltete Verbindung ist für das Modell unsichtbar: Ihre Werkzeuge lassen sich gar nicht aufrufen. Viele haben getrennte Schalter fürs Lesen und fürs Ändern.",
    partsLabel: "Schalter",
    connections: [
      { name: "Dateien", body: "Deine Ordner Schreibtisch, Dokumente und Downloads, sonst nichts.", parts: "Lesen · Schreiben (rückgängig machbar; Gelöschtes geht in den Papierkorb) · Umwandeln (Bilder, Audio, Dokumente)" },
      { name: "Browser", body: "Ein Browser im Vunemi-Fenster, getrennt von deinem Chrome oder Safari. Einmal anmelden, angemeldet bleiben; jederzeit übernehmen.", parts: "Seiten lesen · Klicken und tippen" },
      { name: "Flüge und Hotels", body: "Sucht bei Google Flights und Trivago und zeigt die Optionen als Karten. Mit der Auswahl einer Karte öffnet sich das Angebot neben dem Chat. Route oder Reiseziel, Daten und Personenzahl gehen an Google oder Trivago. Vunemi bucht und bezahlt nicht.", parts: "Google Flights · Trivago" },
      { name: "E-Mail", body: "Die Accounts aus der Mail-App deines Mac (ohne Passwort), Gmail (mit App-Passwort), andere IMAP/SMTP-Konten und Outlook (mit deiner eigenen Microsoft-Entra-App-ID). Ausgehende Mails warten 45 Sekunden im Postausgang. Einmalcodes und Anmeldelinks bekommt das Modell nie zu sehen.", parts: "Lesen · Entwürfe · Senden · Ordnen" },
      { name: "Kalender", body: "Die Kalender auf deinem Mac, auch Google- oder Outlook-Kalender aus den Internetaccounts. Einladen kann es niemanden.", parts: "Lesen · Hinzufügen und ändern (rückgängig machbar)" },
      { name: "Erinnerungen", body: "Die Erinnerungen auf deinem Mac.", parts: "Lesen · Hinzufügen und ändern (rückgängig machbar)" },
      { name: "Mac-Apps", body: "Notizen, Finder, Word, Excel, PowerPoint, Musik, Fotos, Safari, Chrome, Kontakte, Nachrichten und andere skriptfähige Apps, ohne auf den Bildschirm zu klicken.", parts: "Ein Schalter pro App" },
      { name: "Kurzbefehle", body: "Listet deine Apple-Kurzbefehle auf und führt den gewünschten aus.", parts: "Fragt vor jeder Ausführung" },
      { name: "Schreibtisch", body: "Liest App-Fenster und klickt und tippt, wenn du es erlaubst. Terminal, Passwortmanager und Systemeinstellungen sind immer tabu.", parts: "Lesen · Steuern" },
      { name: "Geplante Aufgaben", body: "Aufgaben, die du im Chat einrichtest und die zu festen Zeiten laufen, solange Vunemi geöffnet ist. Sie senden, löschen oder bezahlen nie.", parts: "Einrichten und verwalten" },
      { name: "Verlauf", body: "Findet deine früheren Sitzungen und aufgezeichneten Besprechungen, wenn eine Anfrage sich auf eine bezieht. Jede Anfrage enthält nur Name, Datum und eine Zeile der wenigen passenden; Vunemi liest eine nur bei Bedarf. Nichts verlässt deinen Mac.", parts: "Finden und Lesen" },
      { name: "Eigene Verbindungen", body: "Füge einen beliebigen MCP-Server per Befehl oder Adresse hinzu. Seine Schlüssel liegen im Tresor.", parts: "Ein Schalter pro Verbindung" },
    ],
    safetyTitle: "Sicherheit und Kontrolle",
    safety: [
      { title: "Berechtigungsstufen", body: "Vier Voreinstellungen von „Zusehen und vorschlagen“ bis „Selbstständig handeln“, dazu eine Einstellung pro Art von Aktion. Finanzielle Aktionen sind immer aus." },
      { title: "Tresor", body: "Schlüssel, die Werkzeuge nutzen, werden mit einem Schlüssel aus dem Schlüsselbund deines Macs verschlüsselt. Das Modell sieht nur den Namen." },
      { title: "Aktivitätsprotokoll", body: "Alles, was der Assistent getan hat, auf deinem Mac gespeichert, mit Rückgängig." },
      { title: "Von Vunemi erstellt", body: "Dateien, die es geschrieben, Entwürfe, die es gespeichert, Termine, die es eingetragen, und Dateien, die es geladen hat – mit Öffnen und Im Finder zeigen." },
      { title: "Postausgang", body: "Nachrichten, die auf den Versand warten, und was mit jeder passiert ist." },
      { title: "App-Sperre", body: "Sperre Vunemi mit Touch ID oder deinem Mac-Passwort." },
      { title: "Deine Daten, deine Entscheidung", body: "Vergiss eine Sitzung, eine Notiz oder alles. Eine Notiz aus dem Gedächtnis gewährt nie eine Berechtigung, und Worte aus Seiten, Mails oder Dateien werden nie zu einer." },
    ],
    extras: [
      { title: "Läuft auf deinem Mac", body: "Nutze die eingebaute Engine von Vunemi oder einen Modellserver, den du schon hast: LM Studio, Ollama oder llama.cpp. Du kannst auch eine GGUF-Datei von deinem Mac hinzufügen." },
      { title: "11 Sprachen", body: "Deutsch, Englisch, Türkisch, Französisch, Spanisch, Italienisch, Portugiesisch, Russisch, Chinesisch, Japanisch und Koreanisch." },
    ],
  },
  screensPage: {
    title: "Vunemi-Ansichten",
    intro: "Echte Ansichten der englischen App, mit Beispieldaten aufgenommen. Öffne ein Bild, um es in voller Größe zu sehen.",
  },
  downloadPage: {
    highlightsTitle: "Neu in dieser Version",
    highlights: [
      "Sprachchat: Die Wellenform-Taste neben dem Mikrofon schaltet ihn ein. Vunemi liest seine Antwort Satz für Satz vor, und du kannst ihm ins Wort fallen. Er hört von selbst zu oder nur, wenn du das Mikrofon drückst; sind andere im Raum, wähle das Drücken, denn eine Stimme in deiner Nähe kann für deine gehalten werden.",
      "Besprechungen können die Personen im Gespräch unterscheiden: Person 1, Person 2… Du gibst ihnen Namen und korrigierst, was nicht stimmt. Das bleibt aus, bis du es in Besprechungen einschaltest, braucht einen einmaligen Download und läuft auf deinem Mac.",
      "Persönlichkeit: Schreib unter Einstellungen › Persönlichkeit in deinen eigenen Worten, wie Vunemi mit dir sprechen soll. Das ändert nur Ton und Stil, nie, was Vunemi tun darf.",
      "Der Verlauf zeigt unter jeder gefundenen Sitzung oder Besprechung den Satz, der zu deiner Anfrage passt, und bereitet neue Sitzungen im Hintergrund vor.",
      "Mehr Felder in Webformularen gelten als persönliche Angaben, die Vunemi dir überlässt: ein einfaches Namens- oder Adressfeld neben Kontaktdaten und Telefonnummern. Auch eine in einer Antwort ausgeschriebene Webadresse erhält den Hinweis „ungeprüft“.",
    ],
    title: "Vunemi herunterladen",
    intro: "Kostenlos und Open Source. Für Macs mit Apple Silicon und macOS 14 oder neuer.",
    requirementsTitle: "Du brauchst",
    requirements: ["Einen Mac mit Apple Silicon (M1 oder neuer)", "macOS 14 oder neuer", "Platz für ein Modell: Die App zeigt die Größe jedes Modells vor dem Laden"],
    installTitle: "Installieren",
    install: [
      "Öffne das geladene Disk-Image.",
      "Zieh Vunemi in den Programme-Ordner.",
      "Öffne Vunemi aus dem Programme-Ordner. Sagt macOS, dass es nicht geöffnet werden kann, geh zu Systemeinstellungen › Datenschutz & Sicherheit und klick auf „Dennoch öffnen“.",
      "Wähle auf dem ersten Bildschirm ein Modell. Vunemi schlägt eines vor, das zu deinem Mac passt.",
    ],
    updateTitle: "Aktualisieren",
    updateBody: "Ab 0.1.8 sagt dir Vunemi, wenn eine neue Version da ist, und aktualisiert sich, wenn du auf Aktualisieren klickst. Von einer älteren Version aus lädst du das neue Disk-Image einmal herunter und ziehst Vunemi in den Programme-Ordner; wähle dabei Ersetzen.",
    checksum: "SHA-256",
    notes: "Versionshinweise",
    source: "Quellcode",
    guide: "Leitfaden",
  },
};
