// Reference copy. Every other locale has the same shape (checked at build).
// Facts follow ../PRODUCT.md; don't claim more than it does.
export default {
  langName: "English",
  nav: { home: "Home", features: "What it does", screens: "Screens", download: "Download", guide: "Guide" },
  language: "Language",
  skip: "Skip to content",
  footer: "This site uses no cookies or tracking scripts.",
  demo: {
      "user": "Find the invoices on my Desktop and put them in one folder.",
      "planTitle": "Approve the plan",
      "steps": [
          "Look for invoices on the Desktop",
          "Create a folder called Invoices",
          "Move the invoices into it"
      ],
      "go": "Go ahead",
      "edit": "Edit",
      "cancel": "Cancel",
      "cardTitle": "Move 4 files",
      "cardBody": "Desktop → Documents/Invoices",
      "approve": "Approve",
      "deny": "Deny",
      "done": "Done. The 4 invoices are in Documents/Invoices.",
      "logItem": "Moved 4 files to Invoices",
      "undo": "Undo",
      "model": "Local model",
      "localNote": "The AI model runs on this Mac.",
      "noCloud": "No Vunemi cloud processing"
  },
  meta: {
    home: { title: "Vunemi: a personal assistant that runs on your Mac", description: "Vunemi helps with everyday tasks. Its AI runs on your Mac, without a Vunemi cloud account. You choose which outside services to connect." },
    features: { title: "What Vunemi does", description: "Mail, calendar, files, the web and your Mac apps, with approval cards, undo and hard limits. Everything Vunemi 0.1.14 can do." },
    screens: { title: "Vunemi screens", description: "Real screens from the Vunemi app for Mac, captured with sample data." },
    download: { title: "Download Vunemi for Mac", description: "Download Vunemi 0.1.14 for Apple Silicon Macs with macOS 14 or later. Free and open source." },
  },
  hero: {
    eyebrow: "Personal assistant for Mac",
    title: "Help with everyday tasks. AI runs on your Mac.",
    lead: "Vunemi helps with email, files, your calendar and the web. It asks before changing anything. The AI model runs on your Mac; Vunemi doesn't upload your conversations or documents to its own cloud for processing.",
    download: "Download for Mac",
    explore: "See what it does",
    facts: ["Free and open source", "Apple Silicon", "macOS 14 or later"],
    caption: "Vunemi shows its plan and waits for you",
  },
  strengths: {
    title: "What makes Vunemi different",
    items: [
      { title: "AI runs on your Mac", body: "No Vunemi account or subscription. The AI model processes tasks on your Mac. If you connect Gmail, Outlook or websites, those services exchange the data needed for the task; they aren't Vunemi cloud services." },
      { title: "You have the last word", body: "Every connection starts switched off. Before anything changes, Vunemi shows a card saying exactly what it will do, and waits for you. You choose how often it asks." },
      { title: "Mistakes can be undone", body: "Everything Vunemi does is listed in the Activity log with an Undo button. Deleted files go to the Trash, and a sent email waits 45 seconds so you can take it back." },
    ],
  },
  features: {
    title: "What it helps with",
    intro: "Ask in your own words. Turn on only the connections you need.",
    more: "All features",
    cards: [
      { title: "Stay on top of email", body: "Finds mail waiting for a reply, sums up threads and writes drafts. Works with the accounts in your Mac's Mail app, Gmail, Outlook and other IMAP accounts, and never sends without your approval.", example: "Which emails are waiting for my reply?" },
      { title: "Plan your day", body: "Reads your calendars and reminders, including Google or Outlook calendars added to your Mac, and adds events or to-dos when you approve.", example: "What's on my calendar tomorrow?" },
      { title: "Find and tidy files", body: "Searches your Desktop, Documents and Downloads, reads documents, and moves or renames files after you approve. Every change can be undone.", example: "Find the invoices on my Desktop and put them in one folder." },
      { title: "Look things up on the web", body: "Opens pages in a browser inside Vunemi, separate from your own. It reads, compares and fills in forms, and you can press Take control at any moment.", example: "Compare the opening hours of these three museums." },
      { title: "Use your Mac apps", body: "Works with Notes, Excel, Word, PowerPoint, Finder, Contacts, Messages and more, without clicking around your screen. Each app has its own switch.", example: "Sum up the expenses in this Excel sheet." },
      { title: "Talk instead of typing", body: "Dictate with a speech model that runs on your Mac: you speak, your words appear as text. Voice chat, with spoken answers, is coming in a later release.", example: "Show me today's meetings." },
      { title: "Repeat tasks on a schedule", body: "Ask for a morning summary or a weekly check. Scheduled tasks run while Vunemi is open, and they never send, delete or pay.", example: "Every morning at 9, sum up my calendar." },
      { title: "Show it a picture", body: "Attach a screenshot or a photo. Models that can see images describe them; with other models, Vunemi still reads the text in them on your Mac.", example: "What does the error in this screenshot mean?" },
      { title: "Remembers what you tell it", body: "Tell it how you like to work, or who is who, and it keeps a note in your own words once you say yes. Each answer says which notes it was given; edit or delete them in Settings.", example: "Remember: I want reports as PDF." },
      { title: "Record a meeting", body: "Press Record to capture your microphone and the sound from your Mac. Vunemi writes a transcript and summary on this Mac; after a successful summary, it moves the audio to the Trash. Requires macOS 14.2 or later.", example: "Record this meeting." },
    ],
  },
  screens: {
    title: "See it at work",
    intro: "Real screens from the English app, captured with sample data.",
    more: "All screens",
    captions: {
      home: "Start a task in your own words",
      plan: "Check the plan before anything happens",
      browser: "Reads a web page and answers, in its own browser",
      permissions: "Choose when Vunemi asks first",
      connections: "Every connection starts switched off",
      scheduled: "Scheduled tasks that only read",
      vault: "Keys stay in the Vault; the model sees only the name",
      model: "Pick a model that fits your Mac",
    },
  },
  never: {
    title: "What Vunemi never does",
    intro: "At every permission level. At these steps it stops and hands over to you.",
    items: ["Type passwords, card, bank or ID numbers", "Solve CAPTCHAs", "Pay for anything", "Delete anything for good"],
  },
  start: {
    title: "Get started in three steps",
    steps: [
      { title: "Download and install", body: "Open the disk image and drag Vunemi into the Applications folder." },
      { title: "Choose a model", body: "Vunemi suggests a model that fits your Mac's memory and downloads it. Already use LM Studio or Ollama? Connect that instead." },
      { title: "Turn on what you need", body: "In Settings › Connections, switch on only what you want Vunemi to use." },
    ],
  },
  notes: {
    title: "Good to know",
    items: [
      "Results depend on the model and your Mac. A small model makes more mistakes on complex tasks.",
      "For Apple Silicon Macs with macOS 14 or later.",
      "Tasks, including scheduled ones, run while Vunemi is open.",
      "The app is signed but not yet notarized by Apple. The first time, you may need to click Open Anyway in System Settings › Privacy & Security.",
    ],
  },
  story: {
    eyebrow: "Why Vunemi?",
    title: "Little tasks add up.",
    body: "An email waiting for a reply, a document you can’t find, a crowded calendar. Vunemi is made for those moments: a helper that does the legwork, asks before it acts, and runs its AI on your Mac.",
  },
  community: {
    title: "Open source, built together",
    body: "Vunemi's code is on GitHub under the GPL-3.0 licence. Anyone can read it, check what it does and help make it better.",
    link: "Vunemi on GitHub",
  },
  featuresPage: {
    title: "Everything Vunemi can do",
    intro: "Vunemi 0.1.14 in detail: how you work with it, what it can connect to, and how you stay in control.",
    chatTitle: "Working with Vunemi",
    chat: [
      { title: "Plan first", body: "For a task with several steps, Vunemi can show the plan first. Go ahead, edit the steps or cancel." },
      { title: "Approval cards", body: "Every change comes as a card that says what will happen, where, and to whom." },
      { title: "Queue or interrupt", body: "Type the next request while a task runs. It waits its turn, or interrupt to do it right away." },
      { title: "Emergency stop", body: "⌘⇧Esc stops a running task, even when Vunemi is locked." },
      { title: "Picks up where it left off", body: "If Vunemi closes mid-task, it tells you how far it got and offers to continue, asking before any step that changes or sends." },
      { title: "Projects", body: "Make a folder a project: Vunemi keeps that work's files there, and every change can be undone." },
      { title: "Memory", body: "Notes from your own words, saved only when you say yes. A task gets only the notes that fit it, and the answer says how many it was given." },
    ],
    connTitle: "Connections",
    connIntro: "Each connection is off until you turn it on. A connection that is off is invisible to the model: its tools can't be called at all. Many have separate switches for reading and for changing.",
    partsLabel: "Switches",
    connections: [
      { name: "Files", body: "Your Desktop, Documents and Downloads folders, nothing else.", parts: "Reading · Writing (undoable; deletes go to the Trash) · Converting (images, audio, documents)" },
      { name: "Browser", body: "A browser inside Vunemi's window, separate from your Chrome or Safari. Sign in once and stay signed in; press Take control at any time.", parts: "Reading pages · Clicking and typing" },
      { name: "Flights and hotels", body: "Searches Google Flights and Trivago and shows the options as cards. Choosing a card opens its offer beside the chat. Your route or destination, dates and traveller count go to Google or Trivago. Vunemi does not book or pay.", parts: "Google Flights · Trivago" },
      { name: "Mail", body: "The accounts in the Mac's Mail app (no password needed), Gmail (with an app password), other IMAP/SMTP accounts, and Outlook (with your own Microsoft Entra app ID). Outgoing mail waits 45 seconds in the Outbox. One-time codes and sign-in links are never shown to the model.", parts: "Reading · Drafts · Sending · Organising" },
      { name: "Calendar", body: "The calendars on your Mac, including Google or Outlook calendars added in Internet Accounts. It can't invite anyone.", parts: "Reading · Adding and changing (undoable)" },
      { name: "Reminders", body: "The reminders on your Mac.", parts: "Reading · Adding and changing (undoable)" },
      { name: "Mac apps", body: "Notes, Finder, Word, Excel, PowerPoint, Music, Photos, Safari, Chrome, Contacts, Messages and other scriptable apps, without clicking the screen.", parts: "One switch per app" },
      { name: "Shortcuts", body: "Lists your Apple Shortcuts and runs the one you ask for.", parts: "Every run asks first" },
      { name: "Desktop", body: "Reads app windows and, if you allow it, clicks and types. Terminal, password managers and System Settings are always off limits.", parts: "Reading · Control" },
      { name: "Scheduled tasks", body: "Tasks you set up in chat that run at set times while Vunemi is open. They never send, delete or pay.", parts: "Setting up and managing" },
      { name: "Your own connections", body: "Add any MCP server by command or address. Its keys are kept in the Vault.", parts: "One switch per connection" },
    ],
    safetyTitle: "Safety and control",
    safety: [
      { title: "Permission levels", body: "Four presets, from Watch and suggest to Act on its own, plus a setting for each kind of action. Financial actions are always off." },
      { title: "Vault", body: "Keys that tools use are encrypted with a key in your Mac's Keychain. The model only ever sees the name." },
      { title: "Activity log", body: "Everything the agent did, kept on your Mac, with Undo." },
      { title: "Made by Vunemi", body: "Files it wrote, drafts it saved, events it added and files it downloaded, with Open and Show in Finder." },
      { title: "Outbox", body: "Messages waiting to be sent, and what happened to each." },
      { title: "App lock", body: "Lock Vunemi with Touch ID or your Mac password." },
      { title: "Your data, your call", body: "Forget one session, one note or everything. A note from memory never grants a permission, and words from pages, mail or files can never become one." },
    ],
    extras: [
      { title: "Runs on your Mac", body: "Use Vunemi's built-in engine, or a model server you already have: LM Studio, Ollama or llama.cpp. You can also add a GGUF file from your Mac." },
      { title: "11 languages", body: "English, Turkish, German, French, Spanish, Italian, Portuguese, Russian, Chinese, Japanese and Korean." },
    ],
  },
  screensPage: {
    title: "Vunemi screens",
    intro: "Real screens from the English app, captured with sample data. Open any image to see it full size.",
  },
  downloadPage: {
    title: "Download Vunemi",
    intro: "Free and open source. For Apple Silicon Macs with macOS 14 or later.",
    highlightsTitle: "What's new",
    highlights: [
      "Questions Vunemi asks you come with buttons more reliably, with up to eight choices, and it asks at most two in a row before getting on with the task.",
      "A comparison becomes option cards the right way round, also when the table lists features in rows.",
      "Vunemi notices when a page, a file or a mail has text written as instructions to the assistant. It shows you what it found, treats it as data, and asks before the next action that could send something out.",
      "More kinds of secrets are hidden before the model sees them: keys in JSON, sign-in tokens and passwords inside addresses.",
    ],
    requirementsTitle: "You need",
    requirements: ["A Mac with Apple Silicon (M1 or later)", "macOS 14 or later", "Space for a model: the app shows each model's size before downloading"],
    installTitle: "Install",
    install: [
      "Open the disk image you downloaded.",
      "Drag Vunemi into the Applications folder.",
      "Open Vunemi from Applications. If macOS says it can't be opened, go to System Settings › Privacy & Security and click Open Anyway.",
      "Choose a model on the first screen. Vunemi suggests one that fits your Mac.",
    ],
    updateTitle: "Updating",
    updateBody: "From 0.1.8 on, Vunemi tells you when a new version is out and updates itself when you press Update. From an older version, download the new disk image once and drag Vunemi into Applications, choosing Replace.",
    checksum: "SHA-256",
    notes: "Release notes",
    source: "Source code",
    guide: "Guide",
  },
};
