export default {
  langName: "Español",
  nav: { home: "Inicio", features: "Qué hace", screens: "Pantallas", download: "Descargar", guide: "Guía" },
  language: "Idioma",
  skip: "Ir al contenido",
  footer: "Este sitio no usa cookies ni scripts de seguimiento.",
  demo: {
      "user": "Busca las facturas del Escritorio y ponlas en una carpeta.",
      "planTitle": "Aprueba el plan",
      "steps": [
          "Buscar facturas en el Escritorio",
          "Crear una carpeta llamada Facturas",
          "Mover las facturas a ella"
      ],
      "go": "Adelante",
      "edit": "Editar",
      "cancel": "Cancelar",
      "cardTitle": "Mover 4 archivos",
      "cardBody": "Escritorio → Documentos/Facturas",
      "approve": "Aprobar",
      "deny": "Rechazar",
      "done": "Listo. Las 4 facturas están en Documentos/Facturas.",
      "logItem": "4 archivos movidos a Facturas",
      "undo": "Deshacer",
      "model": "Modelo local",
      "localNote": "El modelo de IA funciona en este Mac.",
      "noCloud": "Sin procesamiento en la nube de Vunemi"
  },
  meta: {
    home: { title: "Vunemi: un asistente personal que funciona en tu Mac", description: "Vunemi ayuda con las tareas diarias. La IA funciona en tu Mac, sin cuenta en la nube de Vunemi. Tú eliges qué servicios externos conectar." },
    features: { title: "Qué hace Vunemi", description: "Correo, calendario, archivos, la web y tus apps del Mac, con tarjetas de aprobación, deshacer y límites claros. Todo lo que puede hacer Vunemi 0.1.13." },
    screens: { title: "Pantallas de Vunemi", description: "Pantallas reales de la app Vunemi para Mac, capturadas con datos de ejemplo." },
    download: { title: "Descarga Vunemi para Mac", description: "Descarga Vunemi 0.1.13 para Mac con Apple Silicon y macOS 14 o posterior. Gratis y de código abierto." },
  },
  hero: {
    eyebrow: "Asistente personal para Mac",
    title: "Ayuda con el día a día. La IA funciona en tu Mac.",
    lead: "Vunemi te ayuda con el correo, los archivos, el calendario y la web. Te pregunta antes de cambiar nada. El modelo de IA funciona en tu Mac; Vunemi no sube tus conversaciones ni documentos a una nube propia para procesarlos.",
    download: "Descargar para Mac",
    explore: "Mira lo que hace",
    facts: ["Gratis y de código abierto", "Apple Silicon", "macOS 14 o posterior"],
    caption: "Vunemi te muestra su plan y te espera",
  },
  strengths: {
    title: "Qué hace diferente a Vunemi",
    items: [
      { title: "La IA funciona en tu Mac", body: "Sin cuenta ni suscripción de Vunemi. El modelo de IA procesa las tareas en tu Mac. Si conectas Gmail, Outlook o sitios web, esos servicios intercambian los datos necesarios para la tarea; no son servicios en la nube de Vunemi." },
      { title: "Tú tienes la última palabra", body: "Todas las conexiones empiezan apagadas. Antes de cambiar algo, Vunemi te muestra una tarjeta que dice exactamente qué va a hacer y espera tu respuesta. Tú eliges con qué frecuencia pregunta." },
      { title: "Los errores se pueden deshacer", body: "Todo lo que hace Vunemi aparece en el Registro de actividad con un botón Deshacer. Los archivos borrados van a la Papelera, y un correo enviado espera 45 segundos por si quieres recuperarlo." },
    ],
  },
  features: {
    title: "En qué te ayuda",
    intro: "Pídeselo con tus propias palabras. Activa solo las conexiones que necesites.",
    more: "Todas las funciones",
    cards: [
      { title: "Lleva al día tu correo", body: "Encuentra los correos que esperan respuesta, resume conversaciones y escribe borradores. Funciona con las cuentas de la app Mail de tu Mac, Gmail, Outlook y otras cuentas IMAP, y nunca envía nada sin tu aprobación.", example: "¿Qué correos esperan mi respuesta?" },
      { title: "Organiza tu día", body: "Lee tus calendarios y recordatorios, incluidos los de Google u Outlook añadidos a tu Mac, y añade eventos o tareas cuando lo apruebas.", example: "¿Qué tengo mañana en el calendario?" },
      { title: "Encuentra y ordena archivos", body: "Busca en tu Escritorio, Documentos y Descargas, lee documentos y mueve o renombra archivos cuando lo apruebas. Todos los cambios se pueden deshacer.", example: "Busca las facturas del Escritorio y ponlas en una carpeta." },
      { title: "Busca en la web", body: "Abre páginas en un navegador dentro de Vunemi, separado del tuyo. Lee, compara y rellena formularios, y puedes pulsar Tomar el control en cualquier momento.", example: "Compara el horario de estos tres museos." },
      { title: "Usa tus apps del Mac", body: "Trabaja con Notas, Excel, Word, PowerPoint, Finder, Contactos, Mensajes y más, sin hacer clic por la pantalla. Cada app tiene su propio interruptor.", example: "Resume los gastos de esta hoja de Excel." },
      { title: "Habla en vez de escribir", body: "Dicta con un modelo de voz que funciona en tu Mac: hablas y tus palabras aparecen como texto. El chat de voz, con respuestas habladas, llegará en una próxima versión.", example: "Muéstrame las reuniones de hoy." },
      { title: "Tareas programadas", body: "Pide un resumen cada mañana o una revisión semanal. Las tareas programadas se ejecutan mientras Vunemi está abierto y nunca envían, borran ni pagan.", example: "Cada mañana a las 9, resume mi calendario." },
      { title: "Enséñale una imagen", body: "Adjunta una captura o una foto. Los modelos que ven imágenes la describen; con otros modelos, Vunemi igualmente lee el texto que contiene en tu Mac.", example: "¿Qué significa el error de esta captura?" },
      { title: "Recuerda lo que le dices", body: "Dile cómo te gusta trabajar, o quién es quién, y lo anota con tus propias palabras cuando das tu visto bueno. Cada respuesta indica qué notas recibió; puedes editarlas o borrarlas en Ajustes.", example: "Recuerda: quiero los informes en PDF." },
      { title: "Grabar una reunión", body: "Pulsa Grabar para captar el micrófono y el sonido del Mac. Vunemi crea una transcripción y un resumen en este Mac; tras resumir, mueve el audio a la Papelera. Requiere macOS 14.2 o posterior.", example: "Grabar esta reunión." },
    ],
  },
  screens: {
    title: "Míralo en acción",
    intro: "Pantallas reales de la app en inglés, capturadas con datos de ejemplo.",
    more: "Todas las pantallas",
    captions: {
      home: "Empieza una tarea con tus propias palabras",
      plan: "Revisa el plan antes de que pase nada",
      browser: "Lee una página web en su propio navegador y responde",
      permissions: "Elige cuándo Vunemi pregunta primero",
      connections: "Todas las conexiones empiezan apagadas",
      scheduled: "Tareas programadas que solo leen",
      vault: "Las claves se quedan en la Bóveda; el modelo solo ve el nombre",
      model: "Elige un modelo adecuado para tu Mac",
    },
  },
  never: {
    title: "Lo que Vunemi nunca hace",
    intro: "Con cualquier nivel de permisos. En estos pasos se detiene y te pasa el control.",
    items: ["Escribir contraseñas ni números de tarjeta, banco o documento de identidad", "Resolver CAPTCHAs", "Pagar nada", "Borrar nada para siempre"],
  },
  start: {
    title: "Empieza en tres pasos",
    steps: [
      { title: "Descarga e instala", body: "Abre la imagen de disco y arrastra Vunemi a la carpeta Aplicaciones." },
      { title: "Elige un modelo", body: "Vunemi te sugiere un modelo adecuado para la memoria de tu Mac y lo descarga. ¿Ya usas LM Studio u Ollama? Conéctalo." },
      { title: "Activa lo que necesites", body: "En Ajustes › Conexiones, activa solo lo que quieras que use Vunemi." },
    ],
  },
  notes: {
    title: "Conviene saber",
    items: [
      "Los resultados dependen del modelo y de tu Mac. Un modelo pequeño se equivoca más en tareas complejas.",
      "Para Mac con Apple Silicon y macOS 14 o posterior.",
      "Las tareas, también las programadas, se ejecutan mientras Vunemi está abierto.",
      "La app está firmada, pero Apple aún no la ha notarizado. La primera vez quizá tengas que pulsar Abrir igualmente en Ajustes del Sistema › Privacidad y seguridad.",
    ],
  },
  story: {
    eyebrow: "¿Por qué Vunemi?",
    title: "Las pequeñas tareas se acumulan.",
    body: "Un correo que espera respuesta, un documento que no encuentras, un calendario lleno. Vunemi está hecho para esos momentos: se ocupa de las tareas pesadas, pregunta antes de actuar y ejecuta la IA en tu Mac.",
  },
  community: {
    title: "Código abierto, hecho entre todos",
    body: "El código de Vunemi está en GitHub con licencia GPL-3.0. Cualquiera puede leerlo, comprobar lo que hace y ayudar a mejorarlo.",
    link: "Vunemi en GitHub",
  },
  featuresPage: {
    title: "Todo lo que puede hacer Vunemi",
    intro: "Vunemi 0.1.13 en detalle: cómo trabajas con él, con qué se puede conectar y cómo mantienes el control.",
    chatTitle: "Trabajar con Vunemi",
    chat: [
      { title: "Primero, el plan", body: "En una tarea de varios pasos, Vunemi puede mostrarte antes el plan. Adelante, edita los pasos o cancela." },
      { title: "Tarjetas de aprobación", body: "Cada cambio llega en una tarjeta que dice qué pasará, dónde y a quién." },
      { title: "Hacer cola o interrumpir", body: "Escribe la siguiente petición mientras una tarea está en marcha. Espera su turno, o interrumpe para hacerla ya." },
      { title: "Parada de emergencia", body: "⌘⇧Esc detiene una tarea en marcha, incluso con Vunemi bloqueado." },
      { title: "Retoma donde lo dejó", body: "Si Vunemi se cierra a mitad de una tarea, te dice hasta dónde llegó y te ofrece continuar, preguntando antes de cualquier paso que cambie o envíe algo." },
      { title: "Proyectos", body: "Convierte una carpeta en proyecto: Vunemi guarda ahí los archivos de ese trabajo y cada cambio se puede deshacer." },
      { title: "Memoria", body: "Notas con tus propias palabras, guardadas solo cuando dices que sí. Una tarea recibe solo las notas que le sirven, y la respuesta dice cuántas recibió." },
    ],
    connTitle: "Conexiones",
    connIntro: "Cada conexión está apagada hasta que la activas. Una conexión apagada es invisible para el modelo: sus herramientas no se pueden usar en absoluto. Muchas tienen interruptores separados para leer y para cambiar.",
    partsLabel: "Interruptores",
    connections: [
      { name: "Archivos", body: "Tus carpetas Escritorio, Documentos y Descargas, nada más.", parts: "Lectura · Escritura (se puede deshacer; lo borrado va a la Papelera) · Conversión (imágenes, audio, documentos)" },
      { name: "Navegador", body: "Un navegador dentro de la ventana de Vunemi, separado de tu Chrome o Safari. Inicia sesión una vez y sigue conectado; toma el control cuando quieras.", parts: "Leer páginas · Hacer clic y escribir" },
      { name: "Vuelos y hoteles", body: "Busca en Google Flights y Trivago y muestra las opciones como tarjetas. Al elegir una tarjeta, su oferta se abre junto al chat. Tu ruta o destino, las fechas y el número de viajeros se envían a Google o a Trivago. Vunemi no reserva ni paga.", parts: "Google Flights · Trivago" },
      { name: "Correo", body: "Las cuentas de la app Mail de tu Mac (sin contraseña), Gmail (con contraseña de aplicación), otras cuentas IMAP/SMTP y Outlook (con tu propio ID de aplicación de Microsoft Entra). El correo saliente espera 45 segundos en la Bandeja de salida. Los códigos de un solo uso y los enlaces de acceso nunca se muestran al modelo.", parts: "Lectura · Borradores · Envío · Organización" },
      { name: "Calendario", body: "Los calendarios de tu Mac, incluidos los de Google u Outlook añadidos en Cuentas de internet. No puede invitar a nadie.", parts: "Lectura · Añadir y cambiar (se puede deshacer)" },
      { name: "Recordatorios", body: "Los recordatorios de tu Mac.", parts: "Lectura · Añadir y cambiar (se puede deshacer)" },
      { name: "Apps del Mac", body: "Notas, Finder, Word, Excel, PowerPoint, Música, Fotos, Safari, Chrome, Contactos, Mensajes y otras apps con soporte de scripts, sin hacer clic en la pantalla.", parts: "Un interruptor por app" },
      { name: "Atajos", body: "Muestra tus Atajos de Apple y ejecuta el que pidas.", parts: "Pregunta antes de cada ejecución" },
      { name: "Escritorio", body: "Lee ventanas de apps y, si lo permites, hace clic y escribe. Terminal, gestores de contraseñas y Ajustes del Sistema están siempre vetados.", parts: "Lectura · Control" },
      { name: "Tareas programadas", body: "Tareas que configuras en el chat y que se ejecutan a horas fijas mientras Vunemi está abierto. Nunca envían, borran ni pagan.", parts: "Configurar y gestionar" },
      { name: "Tus propias conexiones", body: "Añade cualquier servidor MCP con un comando o una dirección. Sus claves se guardan en la Bóveda.", parts: "Un interruptor por conexión" },
    ],
    safetyTitle: "Seguridad y control",
    safety: [
      { title: "Niveles de permiso", body: "Cuatro ajustes, de Observar y sugerir a Actuar por su cuenta, más una opción para cada tipo de acción. Las acciones financieras están siempre desactivadas." },
      { title: "Bóveda", body: "Las claves que usan las herramientas se cifran con una clave del Llavero de tu Mac. El modelo solo ve el nombre." },
      { title: "Registro de actividad", body: "Todo lo que ha hecho el asistente, guardado en tu Mac, con Deshacer." },
      { title: "Hecho por Vunemi", body: "Archivos que escribió, borradores que guardó, eventos que añadió y archivos que descargó, con Abrir y Mostrar en Finder." },
      { title: "Bandeja de salida", body: "Mensajes pendientes de envío y qué pasó con cada uno." },
      { title: "Bloqueo de la app", body: "Bloquea Vunemi con Touch ID o la contraseña de tu Mac." },
      { title: "Tus datos, tu decisión", body: "Olvida una sesión, una nota o todo. Una nota de la memoria nunca concede un permiso, y las palabras de páginas, correos o archivos nunca pueden convertirse en una." },
    ],
    extras: [
      { title: "Funciona en tu Mac", body: "Usa el motor integrado de Vunemi o un servidor de modelos que ya tengas: LM Studio, Ollama o llama.cpp. También puedes añadir un archivo GGUF de tu Mac." },
      { title: "11 idiomas", body: "Español, inglés, turco, alemán, francés, italiano, portugués, ruso, chino, japonés y coreano." },
    ],
  },
  screensPage: {
    title: "Pantallas de Vunemi",
    intro: "Pantallas reales de la app en inglés, capturadas con datos de ejemplo. Abre cualquier imagen para verla a tamaño completo.",
  },
  downloadPage: {
    highlightsTitle: "Novedades de esta versión",
    highlights: [
      "Vunemi ahora propone recordar menos: la forma en que pides una tarea concreta (un formato, un tono, una extensión) ya no se sugiere como preferencia. Sigue proponiendo una nota para lo que dices como regla permanente o dato duradero.",
    ],
    title: "Descarga Vunemi",
    intro: "Gratis y de código abierto. Para Mac con Apple Silicon y macOS 14 o posterior.",
    requirementsTitle: "Necesitas",
    requirements: ["Un Mac con Apple Silicon (M1 o posterior)", "macOS 14 o posterior", "Espacio para un modelo: la app muestra el tamaño de cada modelo antes de descargarlo"],
    installTitle: "Instalar",
    install: [
      "Abre la imagen de disco que descargaste.",
      "Arrastra Vunemi a la carpeta Aplicaciones.",
      "Abre Vunemi desde Aplicaciones. Si macOS dice que no se puede abrir, ve a Ajustes del Sistema › Privacidad y seguridad y pulsa Abrir igualmente.",
      "Elige un modelo en la primera pantalla. Vunemi te sugiere uno adecuado para tu Mac.",
    ],
    updateTitle: "Actualizar",
    updateBody: "Desde la 0.1.8, Vunemi te avisa cuando sale una versión nueva y se actualiza cuando pulsas Actualizar. Desde una versión anterior, descarga una vez la nueva imagen de disco y arrastra Vunemi a Aplicaciones eligiendo Reemplazar.",
    checksum: "SHA-256",
    notes: "Notas de la versión",
    source: "Código fuente",
    guide: "Guía",
  },
};
