export default {
  langName: "Français",
  nav: { home: "Accueil", features: "Fonctions", screens: "Captures", download: "Télécharger", guide: "Guide" },
  language: "Langue",
  skip: "Aller au contenu",
  footer: "Ce site n'utilise ni cookies ni scripts de suivi.",
  demo: {
      "user": "Trouvez les factures sur mon Bureau et rangez-les dans un dossier.",
      "planTitle": "Approuver le plan",
      "steps": [
          "Chercher les factures sur le Bureau",
          "Créer un dossier Factures",
          "Y déplacer les factures"
      ],
      "go": "Continuer",
      "edit": "Modifier",
      "cancel": "Annuler",
      "cardTitle": "Déplacer 4 fichiers",
      "cardBody": "Bureau → Documents/Factures",
      "approve": "Approuver",
      "deny": "Refuser",
      "done": "C'est fait. Les 4 factures sont dans Documents/Factures.",
      "logItem": "4 fichiers déplacés vers Factures",
      "undo": "Annuler",
      "model": "Modèle local",
      "localNote": "Le modèle d’IA fonctionne sur ce Mac.",
      "noCloud": "Aucun traitement dans un cloud Vunemi"
  },
  meta: {
    home: { title: "Vunemi : un assistant personnel qui fonctionne sur votre Mac", description: "Vunemi aide au quotidien. Son IA fonctionne sur votre Mac, sans compte cloud Vunemi. Vous choisissez les services externes à connecter." },
    features: { title: "Ce que fait Vunemi", description: "E-mail, calendrier, fichiers, web et vos apps Mac, avec cartes d'approbation, annulation et limites strictes. Tout ce que sait faire Vunemi 0.1.9." },
    screens: { title: "Captures de Vunemi", description: "De vraies captures de l'app Vunemi pour Mac, réalisées avec des données d'exemple." },
    download: { title: "Télécharger Vunemi pour Mac", description: "Téléchargez Vunemi 0.1.9 pour Mac avec puce Apple et macOS 14 ou ultérieur. Gratuit et open source." },
  },
  hero: {
    eyebrow: "Assistant personnel pour Mac",
    title: "De l’aide au quotidien. L’IA fonctionne sur votre Mac.",
    lead: "Vunemi vous aide avec les e-mails, les fichiers, le calendrier et le web. Il demande avant toute modification. Le modèle d’IA fonctionne sur votre Mac ; Vunemi n’envoie pas vos conversations ou documents vers son propre cloud pour les traiter.",
    download: "Télécharger pour Mac",
    explore: "Voir ce qu'il fait",
    facts: ["Gratuit et open source", "Puce Apple", "macOS 14 ou ultérieur"],
    caption: "Vunemi présente son plan et attend votre accord",
  },
  strengths: {
    title: "Ce qui rend Vunemi différent",
    items: [
      { title: "L’IA fonctionne sur votre Mac", body: "Pas de compte Vunemi ni d’abonnement. Le modèle d’IA traite les tâches sur votre Mac. Si vous connectez Gmail, Outlook ou des sites web, ces services échangent les données nécessaires à la tâche ; ce ne sont pas des services cloud de Vunemi." },
      { title: "Vous avez le dernier mot", body: "Chaque connexion est désactivée au départ. Avant tout changement, Vunemi affiche une carte qui dit exactement ce qu'il va faire, puis attend. Vous choisissez à quelle fréquence il vous demande." },
      { title: "Les erreurs s'annulent", body: "Tout ce que fait Vunemi figure dans le journal d'activité, avec un bouton Annuler. Les fichiers supprimés vont à la Corbeille, et un e-mail envoyé patiente 45 secondes pour que vous puissiez le reprendre." },
    ],
  },
  features: {
    title: "Ce qu'il peut faire pour vous",
    intro: "Demandez avec vos propres mots. N'activez que les connexions dont vous avez besoin.",
    more: "Toutes les fonctions",
    cards: [
      { title: "Suivre vos e-mails", body: "Repère les messages qui attendent une réponse, résume les échanges et rédige des brouillons. Fonctionne avec les comptes de l'app Mail de votre Mac, Gmail, Outlook et d'autres comptes IMAP, et n'envoie jamais rien sans votre accord.", example: "Quels e-mails attendent ma réponse ?" },
      { title: "Organiser votre journée", body: "Lit vos calendriers et rappels, y compris les calendriers Google ou Outlook ajoutés à votre Mac, et ajoute des événements ou des tâches avec votre accord.", example: "Qu'ai-je au programme demain ?" },
      { title: "Retrouver et ranger vos fichiers", body: "Cherche dans le Bureau, Documents et Téléchargements, lit les documents, puis déplace ou renomme des fichiers avec votre accord. Chaque changement peut être annulé.", example: "Trouvez les factures sur mon Bureau et rangez-les dans un dossier." },
      { title: "Chercher sur le web", body: "Ouvre des pages dans un navigateur intégré à Vunemi, distinct du vôtre. Il lit, compare et remplit des formulaires, et vous pouvez reprendre la main à tout moment.", example: "Comparez les horaires de ces trois musées." },
      { title: "Utiliser vos apps Mac", body: "Fonctionne avec Notes, Excel, Word, PowerPoint, Finder, Contacts, Messages et d'autres, sans cliquer partout à l'écran. Chaque app a son propre interrupteur.", example: "Résumez les dépenses de ce tableau Excel." },
      { title: "Parler plutôt qu'écrire", body: "Dictez avec un modèle vocal qui fonctionne sur votre Mac : vous parlez, vos mots s'affichent en texte. Le chat vocal, avec des réponses parlées, arrivera dans une prochaine version.", example: "Montrez-moi les réunions d'aujourd'hui." },
      { title: "Des tâches planifiées", body: "Demandez un résumé chaque matin ou un point hebdomadaire. Les tâches planifiées tournent tant que Vunemi est ouvert et n'envoient, ne suppriment et ne paient jamais rien.", example: "Chaque matin à 9 h, résumez mon calendrier." },
      { title: "Montrez-lui une image", body: "Joignez une capture ou une photo. Les modèles capables de voir les images la décrivent ; avec les autres, Vunemi lit quand même le texte qu'elle contient, sur votre Mac.", example: "Que signifie l'erreur sur cette capture ?" },
      { title: "Retient ce que vous lui dites", body: "Dites-lui comment vous aimez travailler, ou qui est qui : après votre accord, il le note avec vos propres mots. Chaque réponse indique les notes reçues ; modifiez-les ou supprimez-les dans les Réglages.", example: "Retiens : je veux les rapports en PDF." },
      { title: "Enregistrer une réunion", body: "Appuyez sur Enregistrer pour capter le micro et le son du Mac. Vunemi crée une transcription et un résumé sur ce Mac ; après le résumé, il place l’audio dans la Corbeille. Nécessite macOS 14.2 ou ultérieur.", example: "Enregistrer cette réunion." },
    ],
  },
  screens: {
    title: "Vunemi à l'œuvre",
    intro: "De vraies captures de l'app en anglais, réalisées avec des données d'exemple.",
    more: "Toutes les captures",
    captions: {
      home: "Lancez une tâche avec vos propres mots",
      plan: "Vérifiez le plan avant que quoi que ce soit ne se passe",
      browser: "Lit une page web dans son propre navigateur et répond",
      permissions: "Choisissez quand Vunemi vous demande d'abord",
      connections: "Chaque connexion est désactivée au départ",
      scheduled: "Des tâches planifiées qui ne font que lire",
      vault: "Les clés restent dans le Coffre ; le modèle ne voit que le nom",
      model: "Choisissez un modèle adapté à votre Mac",
    },
  },
  never: {
    title: "Ce que Vunemi ne fait jamais",
    intro: "Quel que soit le niveau d'autorisation. À ces étapes, il s'arrête et vous passe la main.",
    items: ["Saisir des mots de passe ou des numéros de carte, de compte ou d'identité", "Résoudre des CAPTCHA", "Payer quoi que ce soit", "Supprimer quoi que ce soit définitivement"],
  },
  start: {
    title: "Commencer en trois étapes",
    steps: [
      { title: "Téléchargez et installez", body: "Ouvrez l'image disque et faites glisser Vunemi dans le dossier Applications." },
      { title: "Choisissez un modèle", body: "Vunemi propose un modèle adapté à la mémoire de votre Mac et le télécharge. Vous utilisez déjà LM Studio ou Ollama ? Connectez-le." },
      { title: "Activez l'essentiel", body: "Dans Réglages › Connexions, n'activez que ce que Vunemi doit utiliser." },
    ],
  },
  notes: {
    title: "Bon à savoir",
    items: [
      "Les résultats dépendent du modèle et de votre Mac. Un petit modèle se trompe davantage sur les tâches complexes.",
      "Pour les Mac avec puce Apple et macOS 14 ou ultérieur.",
      "Les tâches, y compris planifiées, s'exécutent tant que Vunemi est ouvert.",
      "L'app est signée mais pas encore notarisée par Apple. La première fois, vous devrez peut-être cliquer sur Ouvrir quand même dans Réglages Système › Confidentialité et sécurité.",
    ],
  },
  story: {
    eyebrow: "Pourquoi Vunemi ?",
    title: "Les petites tâches s'accumulent.",
    body: "Un e-mail attend une réponse, un document reste introuvable, le calendrier est chargé. Vunemi est conçu pour ces moments : il prend en charge les corvées, demande avant d’agir et exécute l’IA sur votre Mac.",
  },
  community: {
    title: "Open source, construit ensemble",
    body: "Le code de Vunemi est sur GitHub sous licence GPL-3.0. Chacun peut le lire, vérifier ce qu'il fait et aider à l'améliorer.",
    link: "Vunemi sur GitHub",
  },
  featuresPage: {
    title: "Tout ce que Vunemi sait faire",
    intro: "Vunemi 0.1.9 en détail : comment travailler avec lui, à quoi il peut se connecter et comment vous gardez le contrôle.",
    chatTitle: "Travailler avec Vunemi",
    chat: [
      { title: "D'abord le plan", body: "Pour une tâche en plusieurs étapes, Vunemi peut d'abord présenter son plan. Lancez-le, modifiez les étapes ou annulez." },
      { title: "Cartes d'approbation", body: "Chaque changement arrive sous forme de carte qui indique ce qui va se passer, où et pour qui." },
      { title: "File d'attente ou interruption", body: "Tapez la demande suivante pendant qu'une tâche tourne. Elle attend son tour, ou vous interrompez pour la traiter tout de suite." },
      { title: "Arrêt d'urgence", body: "⌘⇧Échap arrête une tâche en cours, même quand Vunemi est verrouillé." },
      { title: "Reprend là où il s'était arrêté", body: "Si Vunemi se ferme en pleine tâche, il vous dit où il en était et propose de continuer, en demandant avant toute étape qui modifie ou envoie." },
      { title: "Projets", body: "Faites d'un dossier un projet : Vunemi y garde les fichiers de ce travail, et chaque changement peut être annulé." },
      { title: "Mémoire", body: "Des notes tirées de vos propres mots, enregistrées seulement avec votre accord. Une tâche ne reçoit que les notes utiles, et la réponse indique combien." },
    ],
    connTitle: "Connexions",
    connIntro: "Chaque connexion reste désactivée tant que vous ne l'activez pas. Une connexion désactivée est invisible pour le modèle : ses outils ne peuvent pas être appelés du tout. Beaucoup ont des interrupteurs distincts pour la lecture et la modification.",
    partsLabel: "Interrupteurs",
    connections: [
      { name: "Fichiers", body: "Vos dossiers Bureau, Documents et Téléchargements, rien d'autre.", parts: "Lecture · Écriture (annulable ; les suppressions vont à la Corbeille) · Conversion (images, audio, documents)" },
      { name: "Navigateur", body: "Un navigateur dans la fenêtre de Vunemi, distinct de votre Chrome ou Safari. Connectez-vous une fois et restez connecté ; reprenez la main quand vous voulez.", parts: "Lecture des pages · Clics et saisie" },
      { name: "Vols et hôtels", body: "Recherche sur Google Flights et Trivago et présente les options sous forme de cartes. Choisir une carte ouvre son offre à côté de la conversation. Votre itinéraire ou destination, vos dates et le nombre de voyageurs sont envoyés à Google ou à Trivago. Vunemi ne réserve pas et ne paie pas.", parts: "Google Flights · Trivago" },
      { name: "E-mail", body: "Les comptes de l'app Mail de votre Mac (sans mot de passe), Gmail (avec un mot de passe d'application), d'autres comptes IMAP/SMTP et Outlook (avec votre propre ID d'application Microsoft Entra). Le courrier sortant attend 45 secondes dans la boîte d'envoi. Les codes à usage unique et les liens de connexion ne sont jamais montrés au modèle.", parts: "Lecture · Brouillons · Envoi · Classement" },
      { name: "Calendrier", body: "Les calendriers de votre Mac, y compris Google ou Outlook ajoutés dans Comptes Internet. Il ne peut inviter personne.", parts: "Lecture · Ajout et modification (annulable)" },
      { name: "Rappels", body: "Les rappels de votre Mac.", parts: "Lecture · Ajout et modification (annulable)" },
      { name: "Apps Mac", body: "Notes, Finder, Word, Excel, PowerPoint, Musique, Photos, Safari, Chrome, Contacts, Messages et d'autres apps scriptables, sans cliquer à l'écran.", parts: "Un interrupteur par app" },
      { name: "Raccourcis", body: "Liste vos Raccourcis Apple et exécute celui que vous demandez.", parts: "Demande avant chaque exécution" },
      { name: "Bureau", body: "Lit les fenêtres des apps et, si vous l'autorisez, clique et tape. Terminal, gestionnaires de mots de passe et Réglages Système sont toujours exclus.", parts: "Lecture · Contrôle" },
      { name: "Tâches planifiées", body: "Des tâches créées dans le chat, qui s'exécutent à heure fixe tant que Vunemi est ouvert. Elles n'envoient, ne suppriment et ne paient jamais rien.", parts: "Création et gestion" },
      { name: "Vos propres connexions", body: "Ajoutez n'importe quel serveur MCP par commande ou par adresse. Ses clés sont conservées dans le Coffre.", parts: "Un interrupteur par connexion" },
    ],
    safetyTitle: "Sécurité et contrôle",
    safety: [
      { title: "Niveaux d'autorisation", body: "Quatre préréglages, d'Observer et suggérer à Agir seul, plus un réglage par type d'action. Les opérations financières sont toujours désactivées." },
      { title: "Coffre", body: "Les clés utilisées par les outils sont chiffrées avec une clé du trousseau de votre Mac. Le modèle ne voit jamais que le nom." },
      { title: "Journal d'activité", body: "Tout ce que l'assistant a fait, conservé sur votre Mac, avec Annuler." },
      { title: "Créé par Vunemi", body: "Les fichiers qu'il a écrits, les brouillons enregistrés, les événements ajoutés et les fichiers téléchargés, avec Ouvrir et Afficher dans le Finder." },
      { title: "Boîte d'envoi", body: "Les messages en attente d'envoi et ce qu'il est advenu de chacun." },
      { title: "Verrouillage", body: "Verrouillez Vunemi avec Touch ID ou le mot de passe de votre Mac." },
      { title: "Vos données, votre choix", body: "Oubliez une session, une note ou tout. Une note de la mémoire n'accorde jamais d'autorisation, et les mots d'une page, d'un e-mail ou d'un fichier ne peuvent jamais en devenir une." },
    ],
    extras: [
      { title: "Fonctionne sur votre Mac", body: "Utilisez le moteur intégré de Vunemi ou un serveur de modèles que vous avez déjà : LM Studio, Ollama ou llama.cpp. Vous pouvez aussi ajouter un fichier GGUF de votre Mac." },
      { title: "11 langues", body: "Français, anglais, turc, allemand, espagnol, italien, portugais, russe, chinois, japonais et coréen." },
    ],
  },
  screensPage: {
    title: "Captures de Vunemi",
    intro: "De vraies captures de l'app en anglais, réalisées avec des données d'exemple. Ouvrez une image pour la voir en grand.",
  },
  downloadPage: {
    highlightsTitle: "Nouveautés de cette version",
    highlights: [
      "Recherchez des vols sur Google Flights et des hôtels sur Trivago : les options arrivent sous forme de cartes, et en choisir une ouvre son offre à côté de la conversation. Les deux connexions sont désactivées au départ.",
      "Vunemi ne réserve pas et ne paie pas à votre place : la connexion et le paiement restent entre vos mains.",
      "Une barre latérale plus sobre : la note indiquant que le modèle et vos données restent sur ce Mac devient une icône de cadenas à côté du modèle.",
    ],
    title: "Télécharger Vunemi",
    intro: "Gratuit et open source. Pour les Mac avec puce Apple et macOS 14 ou ultérieur.",
    requirementsTitle: "Il vous faut",
    requirements: ["Un Mac avec puce Apple (M1 ou ultérieur)", "macOS 14 ou ultérieur", "De la place pour un modèle : l'app affiche la taille de chaque modèle avant le téléchargement"],
    installTitle: "Installation",
    install: [
      "Ouvrez l'image disque téléchargée.",
      "Faites glisser Vunemi dans le dossier Applications.",
      "Ouvrez Vunemi depuis Applications. Si macOS indique qu'il ne peut pas être ouvert, allez dans Réglages Système › Confidentialité et sécurité et cliquez sur Ouvrir quand même.",
      "Choisissez un modèle sur le premier écran. Vunemi en propose un adapté à votre Mac.",
    ],
    updateTitle: "Mise à jour",
    updateBody: "À partir de 0.1.8, Vunemi vous prévient quand une nouvelle version sort et se met à jour quand vous appuyez sur Mettre à jour. Depuis une version plus ancienne, téléchargez une fois la nouvelle image disque et faites glisser Vunemi dans Applications en choisissant Remplacer.",
    checksum: "SHA-256",
    notes: "Notes de version",
    source: "Code source",
    guide: "Guide",
  },
};
