export default {
  langName: "Italiano",
  nav: { home: "Home", features: "Cosa fa", screens: "Schermate", download: "Scarica", guide: "Guida" },
  language: "Lingua",
  skip: "Vai al contenuto",
  footer: "Questo sito non usa cookie né script di tracciamento.",
  demo: {
      "user": "Trova le fatture sulla Scrivania e mettile in una cartella.",
      "planTitle": "Approva il piano",
      "steps": [
          "Cercare le fatture sulla Scrivania",
          "Creare una cartella Fatture",
          "Spostarci le fatture"
      ],
      "go": "Procedi",
      "edit": "Modifica",
      "cancel": "Annulla",
      "cardTitle": "Sposta 4 file",
      "cardBody": "Scrivania → Documenti/Fatture",
      "approve": "Approva",
      "deny": "Rifiuta",
      "done": "Fatto. Le 4 fatture sono in Documenti/Fatture.",
      "logItem": "4 file spostati in Fatture",
      "undo": "Annulla",
      "model": "Modello locale",
      "localNote": "Il modello di IA funziona su questo Mac.",
      "noCloud": "Nessuna elaborazione nel cloud di Vunemi"
  },
  meta: {
    home: { title: "Vunemi: un assistente personale che funziona sul tuo Mac", description: "Vunemi aiuta nelle attività quotidiane. L’IA funziona sul tuo Mac, senza account cloud Vunemi. Scegli tu quali servizi esterni collegare." },
    features: { title: "Cosa fa Vunemi", description: "Email, calendario, file, web e le tue app per Mac, con schede di approvazione, annulla e limiti precisi. Tutto ciò che fa Vunemi 0.1.14." },
    screens: { title: "Schermate di Vunemi", description: "Schermate reali dell'app Vunemi per Mac, catturate con dati di esempio." },
    download: { title: "Scarica Vunemi per Mac", description: "Scarica Vunemi 0.1.14 per Mac con Apple Silicon e macOS 14 o successivo. Gratuito e open source." },
  },
  hero: {
    eyebrow: "Assistente personale per Mac",
    title: "Un aiuto ogni giorno. L’IA funziona sul tuo Mac.",
    lead: "Vunemi ti aiuta con email, file, calendario e web. Chiede prima di cambiare qualcosa. Il modello di IA funziona sul tuo Mac; Vunemi non carica conversazioni o documenti su un proprio cloud per elaborarli.",
    download: "Scarica per Mac",
    explore: "Scopri cosa fa",
    facts: ["Gratuito e open source", "Apple Silicon", "macOS 14 o successivo"],
    caption: "Vunemi ti mostra il piano e ti aspetta",
  },
  strengths: {
    title: "Cosa rende Vunemi diverso",
    items: [
      { title: "L’IA funziona sul tuo Mac", body: "Nessun account Vunemi né abbonamento. Il modello di IA elabora le attività sul tuo Mac. Se colleghi Gmail, Outlook o siti web, questi servizi scambiano i dati necessari all’attività; non sono servizi cloud di Vunemi." },
      { title: "L'ultima parola è tua", body: "Ogni connessione parte spenta. Prima di cambiare qualcosa, Vunemi ti mostra una scheda che dice esattamente cosa farà, e aspetta. Sei tu a scegliere quanto spesso chiede." },
      { title: "Gli errori si possono annullare", body: "Tutto ciò che fa Vunemi compare nel Registro attività con un pulsante Annulla. I file eliminati finiscono nel Cestino, e un'email inviata aspetta 45 secondi così puoi ritirarla." },
    ],
  },
  features: {
    title: "In cosa ti aiuta",
    intro: "Chiedi con parole tue. Attiva solo le connessioni che ti servono.",
    more: "Tutte le funzioni",
    cards: [
      { title: "Tieni in ordine la posta", body: "Trova le email che aspettano risposta, riassume le conversazioni e scrive bozze. Funziona con gli account dell'app Mail del tuo Mac, Gmail, Outlook e altri account IMAP, e non invia mai senza la tua approvazione.", example: "Quali email aspettano una mia risposta?" },
      { title: "Organizza la giornata", body: "Legge calendari e promemoria, compresi i calendari Google o Outlook aggiunti al Mac, e aggiunge eventi o attività quando approvi.", example: "Cosa ho in calendario domani?" },
      { title: "Trova e ordina i file", body: "Cerca in Scrivania, Documenti e Download, legge i documenti e sposta o rinomina i file dopo la tua approvazione. Ogni modifica si può annullare.", example: "Trova le fatture sulla Scrivania e mettile in una cartella." },
      { title: "Cerca sul web", body: "Apre le pagine in un browser dentro Vunemi, separato dal tuo. Legge, confronta e compila moduli, e puoi premere Prendi il controllo in qualsiasi momento.", example: "Confronta gli orari di questi tre musei." },
      { title: "Usa le app del Mac", body: "Funziona con Note, Excel, Word, PowerPoint, Finder, Contatti, Messaggi e altre, senza cliccare in giro sullo schermo. Ogni app ha il suo interruttore.", example: "Riassumi le spese di questo foglio Excel." },
      { title: "Parla invece di scrivere", body: "Detta con un modello vocale che funziona sul tuo Mac: parli e le tue parole diventano testo. La chat vocale, con risposte parlate, arriverà in una prossima versione.", example: "Mostrami le riunioni di oggi." },
      { title: "Attività programmate", body: "Chiedi un riepilogo ogni mattina o un controllo settimanale. Le attività programmate funzionano mentre Vunemi è aperto e non inviano, eliminano né pagano mai.", example: "Ogni mattina alle 9 riassumi il mio calendario." },
      { title: "Mostragli un'immagine", body: "Allega uno screenshot o una foto. I modelli che vedono le immagini la descrivono; con gli altri, Vunemi legge comunque il testo che contiene, sul tuo Mac.", example: "Cosa significa l'errore in questo screenshot?" },
      { title: "Ricorda ciò che gli dici", body: "Digli come ti piace lavorare, o chi è chi, e lo annota con le tue parole quando dai l'ok. Ogni risposta indica quali note ha ricevuto; puoi modificarle o eliminarle nelle Impostazioni.", example: "Ricorda: voglio i report in PDF." },
      { title: "Registra una riunione", body: "Premi Registra per acquisire il microfono e l’audio del Mac. Vunemi crea trascrizione e riepilogo su questo Mac; dopo il riepilogo sposta l’audio nel Cestino. Richiede macOS 14.2 o successivo.", example: "Registra questa riunione." },
    ],
  },
  screens: {
    title: "Guardalo all'opera",
    intro: "Schermate reali dell'app in inglese, catturate con dati di esempio.",
    more: "Tutte le schermate",
    captions: {
      home: "Avvia un'attività con parole tue",
      plan: "Controlla il piano prima che succeda qualcosa",
      browser: "Legge una pagina web nel suo browser e risponde",
      permissions: "Scegli quando Vunemi deve chiedere prima",
      connections: "Ogni connessione parte spenta",
      scheduled: "Attività programmate che si limitano a leggere",
      vault: "Le chiavi restano nella Cassaforte; il modello vede solo il nome",
      model: "Scegli un modello adatto al tuo Mac",
    },
  },
  never: {
    title: "Cosa Vunemi non fa mai",
    intro: "A qualsiasi livello di permessi. In questi passaggi si ferma e passa a te.",
    items: ["Inserire password o numeri di carta, conto o documento", "Risolvere CAPTCHA", "Pagare qualcosa", "Eliminare qualcosa per sempre"],
  },
  start: {
    title: "Inizia in tre passi",
    steps: [
      { title: "Scarica e installa", body: "Apri l'immagine disco e trascina Vunemi nella cartella Applicazioni." },
      { title: "Scegli un modello", body: "Vunemi ti propone un modello adatto alla memoria del tuo Mac e lo scarica. Usi già LM Studio o Ollama? Collegalo." },
      { title: "Attiva ciò che ti serve", body: "In Impostazioni › Connessioni, attiva solo ciò che vuoi far usare a Vunemi." },
    ],
  },
  notes: {
    title: "Buono a sapersi",
    items: [
      "I risultati dipendono dal modello e dal tuo Mac. Un modello piccolo sbaglia di più nelle attività complesse.",
      "Per Mac con Apple Silicon e macOS 14 o successivo.",
      "Le attività, anche quelle programmate, funzionano mentre Vunemi è aperto.",
      "L'app è firmata ma non ancora notarizzata da Apple. La prima volta potresti dover fare clic su Apri comunque in Impostazioni di Sistema › Privacy e sicurezza.",
    ],
  },
  story: {
    eyebrow: "Perché Vunemi?",
    title: "Le piccole cose si accumulano.",
    body: "Un’email in attesa di risposta, un documento introvabile, il calendario pieno. Vunemi nasce per questi momenti: si occupa delle incombenze, chiede prima di agire e fa funzionare l’IA sul tuo Mac.",
  },
  community: {
    title: "Open source, costruito insieme",
    body: "Il codice di Vunemi è su GitHub con licenza GPL-3.0. Chiunque può leggerlo, verificare cosa fa e contribuire a migliorarlo.",
    link: "Vunemi su GitHub",
  },
  featuresPage: {
    title: "Tutto ciò che Vunemi sa fare",
    intro: "Vunemi 0.1.14 nel dettaglio: come lavori con lui, a cosa si collega e come mantieni il controllo.",
    chatTitle: "Lavorare con Vunemi",
    chat: [
      { title: "Prima il piano", body: "Per un'attività con più passaggi, Vunemi può mostrarti prima il piano. Vai avanti, modifica i passaggi o annulla." },
      { title: "Schede di approvazione", body: "Ogni modifica arriva come una scheda che dice cosa succederà, dove e a chi." },
      { title: "In coda o subito", body: "Scrivi la richiesta successiva mentre un'attività è in corso. Aspetta il suo turno, oppure interrompi per farla subito." },
      { title: "Arresto di emergenza", body: "⌘⇧Esc ferma un'attività in corso, anche quando Vunemi è bloccato." },
      { title: "Riprende da dove si era fermato", body: "Se Vunemi si chiude a metà di un'attività, ti dice fin dove è arrivato e propone di continuare, chiedendo prima di ogni passaggio che modifica o invia." },
      { title: "Progetti", body: "Trasforma una cartella in progetto: Vunemi tiene lì i file di quel lavoro, e ogni modifica si può annullare." },
      { title: "Memoria", body: "Note tratte dalle tue parole, salvate solo quando dici di sì. Un'attività riceve solo le note che le servono, e la risposta dice quante ne ha ricevute." },
    ],
    connTitle: "Connessioni",
    connIntro: "Ogni connessione resta spenta finché non la attivi. Una connessione spenta è invisibile al modello: i suoi strumenti non si possono proprio usare. Molte hanno interruttori separati per leggere e per modificare.",
    partsLabel: "Interruttori",
    connections: [
      { name: "File", body: "Le cartelle Scrivania, Documenti e Download, nient'altro.", parts: "Lettura · Scrittura (annullabile; ciò che elimini va nel Cestino) · Conversione (immagini, audio, documenti)" },
      { name: "Browser", body: "Un browser nella finestra di Vunemi, separato dal tuo Chrome o Safari. Accedi una volta e resti connesso; prendi il controllo quando vuoi.", parts: "Lettura delle pagine · Clic e digitazione" },
      { name: "Voli e hotel", body: "Cerca su Google Flights e Trivago e mostra le opzioni come schede. Scegliendo una scheda, la sua offerta si apre accanto alla chat. Tratta o destinazione, date e numero di viaggiatori vanno a Google o a Trivago. Vunemi non prenota e non paga.", parts: "Google Flights · Trivago" },
      { name: "Email", body: "Gli account dell'app Mail del tuo Mac (senza password), Gmail (con password per app), altri account IMAP/SMTP e Outlook (con il tuo ID applicazione Microsoft Entra). La posta in uscita aspetta 45 secondi nella Posta in uscita. Codici monouso e link di accesso non vengono mai mostrati al modello.", parts: "Lettura · Bozze · Invio · Organizzazione" },
      { name: "Calendario", body: "I calendari del tuo Mac, compresi quelli Google o Outlook aggiunti in Account Internet. Non può invitare nessuno.", parts: "Lettura · Aggiunta e modifica (annullabile)" },
      { name: "Promemoria", body: "I promemoria del tuo Mac.", parts: "Lettura · Aggiunta e modifica (annullabile)" },
      { name: "App del Mac", body: "Note, Finder, Word, Excel, PowerPoint, Musica, Foto, Safari, Chrome, Contatti, Messaggi e altre app programmabili, senza cliccare sullo schermo.", parts: "Un interruttore per app" },
      { name: "Comandi rapidi", body: "Elenca i tuoi Comandi rapidi di Apple ed esegue quello che chiedi.", parts: "Chiede prima di ogni esecuzione" },
      { name: "Scrivania", body: "Legge le finestre delle app e, se lo permetti, fa clic e digita. Terminale, gestori di password e Impostazioni di Sistema sono sempre esclusi.", parts: "Lettura · Controllo" },
      { name: "Attività programmate", body: "Attività impostate in chat che partono a orari fissi mentre Vunemi è aperto. Non inviano, eliminano né pagano mai.", parts: "Impostazione e gestione" },
      { name: "Connessioni tue", body: "Aggiungi qualsiasi server MCP tramite comando o indirizzo. Le sue chiavi sono conservate nella Cassaforte.", parts: "Un interruttore per connessione" },
    ],
    safetyTitle: "Sicurezza e controllo",
    safety: [
      { title: "Livelli di permesso", body: "Quattro preimpostazioni, da Osserva e suggerisci ad Agisci da solo, più un'impostazione per ogni tipo di azione. Le operazioni finanziarie sono sempre disattivate." },
      { title: "Cassaforte", body: "Le chiavi usate dagli strumenti sono cifrate con una chiave del Portachiavi del tuo Mac. Il modello vede solo il nome." },
      { title: "Registro attività", body: "Tutto ciò che ha fatto l'assistente, salvato sul tuo Mac, con Annulla." },
      { title: "Creato da Vunemi", body: "I file che ha scritto, le bozze salvate, gli eventi aggiunti e i file scaricati, con Apri e Mostra nel Finder." },
      { title: "Posta in uscita", body: "I messaggi in attesa di invio e cosa è successo a ciascuno." },
      { title: "Blocco dell'app", body: "Blocca Vunemi con Touch ID o la password del Mac." },
      { title: "I tuoi dati, la tua scelta", body: "Dimentica una sessione, una nota o tutto. Una nota della memoria non concede mai un permesso, e le parole di pagine, email o file non possono mai diventarne una." },
    ],
    extras: [
      { title: "Funziona sul tuo Mac", body: "Usa il motore integrato di Vunemi o un server di modelli che hai già: LM Studio, Ollama o llama.cpp. Puoi anche aggiungere un file GGUF dal tuo Mac." },
      { title: "11 lingue", body: "Italiano, inglese, turco, tedesco, francese, spagnolo, portoghese, russo, cinese, giapponese e coreano." },
    ],
  },
  screensPage: {
    title: "Schermate di Vunemi",
    intro: "Schermate reali dell'app in inglese, catturate con dati di esempio. Apri un'immagine per vederla a grandezza piena.",
  },
  downloadPage: {
    highlightsTitle: "Novità di questa versione",
    highlights: [
      "Le domande che Vunemi ti fa arrivano con i pulsanti in modo più affidabile, con fino a otto scelte, e ne fa al massimo due di fila prima di proseguire con l'attività.",
      "Un confronto diventa schede di opzioni nel verso giusto, anche quando la tabella elenca le caratteristiche nelle righe.",
      "Vunemi si accorge quando una pagina, un file o un'e-mail contiene un testo scritto come istruzioni per l'assistente. Ti mostra che cosa ha trovato, lo tratta come dati e ti chiede prima della prossima azione che potrebbe inviare qualcosa all'esterno.",
      "Più tipi di segreti vengono nascosti prima che il modello li veda: chiavi in JSON, token di accesso e password dentro gli indirizzi.",
    ],
    title: "Scarica Vunemi",
    intro: "Gratuito e open source. Per Mac con Apple Silicon e macOS 14 o successivo.",
    requirementsTitle: "Ti serve",
    requirements: ["Un Mac con Apple Silicon (M1 o successivo)", "macOS 14 o successivo", "Spazio per un modello: l'app mostra la dimensione di ogni modello prima di scaricarlo"],
    installTitle: "Installazione",
    install: [
      "Apri l'immagine disco scaricata.",
      "Trascina Vunemi nella cartella Applicazioni.",
      "Apri Vunemi da Applicazioni. Se macOS dice che non può essere aperto, vai in Impostazioni di Sistema › Privacy e sicurezza e fai clic su Apri comunque.",
      "Scegli un modello nella prima schermata. Vunemi ne propone uno adatto al tuo Mac.",
    ],
    updateTitle: "Aggiornare",
    updateBody: "Dalla 0.1.8 Vunemi ti avvisa quando esce una nuova versione e si aggiorna quando premi Aggiorna. Da una versione precedente, scarica una volta la nuova immagine disco e trascina Vunemi in Applicazioni scegliendo Sostituisci.",
    checksum: "SHA-256",
    notes: "Note di rilascio",
    source: "Codice sorgente",
    guide: "Guida",
  },
};
