export default {
  langName: "Português",
  nav: { home: "Início", features: "O que faz", screens: "Telas", download: "Baixar", guide: "Guia" },
  language: "Idioma",
  skip: "Pular para o conteúdo",
  footer: "Este site não usa cookies nem scripts de rastreamento.",
  demo: {
      "user": "Encontre as notas fiscais na Mesa e junte numa pasta.",
      "planTitle": "Aprove o plano",
      "steps": [
          "Procurar notas fiscais na Mesa",
          "Criar uma pasta chamada Notas",
          "Mover as notas para ela"
      ],
      "go": "Seguir",
      "edit": "Editar",
      "cancel": "Cancelar",
      "cardTitle": "Mover 4 arquivos",
      "cardBody": "Mesa → Documentos/Notas",
      "approve": "Aprovar",
      "deny": "Recusar",
      "done": "Pronto. As 4 notas estão em Documentos/Notas.",
      "logItem": "4 arquivos movidos para Notas",
      "undo": "Desfazer",
      "model": "Modelo local",
      "localNote": "O modelo de IA roda neste Mac.",
      "noCloud": "Sem processamento na nuvem do Vunemi"
  },
  meta: {
    home: { title: "Vunemi: um assistente pessoal que roda no seu Mac", description: "O Vunemi ajuda nas tarefas do dia a dia. A IA roda no seu Mac, sem conta na nuvem do Vunemi. Você escolhe quais serviços externos conectar." },
    features: { title: "O que o Vunemi faz", description: "E-mail, agenda, arquivos, a web e seus apps do Mac, com cartões de aprovação, desfazer e limites claros. Tudo o que o Vunemi 0.1.19 faz." },
    screens: { title: "Telas do Vunemi", description: "Telas reais do app Vunemi para Mac, capturadas com dados de exemplo." },
    download: { title: "Baixe o Vunemi para Mac", description: "Baixe o Vunemi 0.1.19 para Macs com Apple Silicon e macOS 14 ou posterior. Gratuito e de código aberto." },
  },
  hero: {
    eyebrow: "Assistente pessoal para Mac",
    title: "Ajuda no dia a dia. A IA roda no seu Mac.",
    lead: "O Vunemi ajuda com e-mails, arquivos, agenda e web. Ele pergunta antes de mudar qualquer coisa. O modelo de IA roda no seu Mac; o Vunemi não envia conversas ou documentos para uma nuvem própria para processá-los.",
    download: "Baixar para Mac",
    explore: "Veja o que ele faz",
    facts: ["Gratuito e de código aberto", "Apple Silicon", "macOS 14 ou posterior"],
    caption: "O Vunemi mostra o plano e espera por você",
  },
  strengths: {
    title: "O que torna o Vunemi diferente",
    items: [
      { title: "A IA roda no seu Mac", body: "Sem conta ou assinatura do Vunemi. O modelo de IA processa as tarefas no seu Mac. Se você conectar Gmail, Outlook ou sites, esses serviços trocam os dados necessários à tarefa; não são serviços de nuvem do Vunemi." },
      { title: "A última palavra é sua", body: "Toda conexão começa desligada. Antes de mudar algo, o Vunemi mostra um cartão dizendo exatamente o que vai fazer e espera por você. Você escolhe com que frequência ele pergunta." },
      { title: "Erros podem ser desfeitos", body: "Tudo o que o Vunemi faz aparece no Registro de atividades com um botão Desfazer. Arquivos apagados vão para o Lixo, e um e-mail enviado espera 45 segundos para você poder cancelá-lo." },
    ],
  },
  features: {
    title: "No que ele ajuda",
    intro: "Peça com suas próprias palavras. Ligue só as conexões de que você precisa.",
    more: "Todos os recursos",
    cards: [
      { title: "Fique em dia com os e-mails", body: "Encontra e-mails esperando resposta, resume conversas e escreve rascunhos. Funciona com as contas do app Mail do seu Mac, Gmail, Outlook e outras contas IMAP, e nunca envia nada sem a sua aprovação.", example: "Quais e-mails estão esperando minha resposta?" },
      { title: "Planeje o seu dia", body: "Lê suas agendas e lembretes, incluindo agendas do Google ou do Outlook adicionadas ao Mac, e cria eventos ou tarefas quando você aprova.", example: "O que tenho na agenda amanhã?" },
      { title: "Encontre e organize arquivos", body: "Procura na Mesa, em Documentos e em Downloads, lê documentos e move ou renomeia arquivos depois da sua aprovação. Toda mudança pode ser desfeita.", example: "Encontre as notas fiscais na Mesa e junte numa pasta." },
      { title: "Pesquise na web", body: "Abre páginas num navegador dentro do Vunemi, separado do seu. Lê, compara e preenche formulários, e você pode clicar em Assumir o controle a qualquer momento.", example: "Compare o horário destes três museus." },
      { title: "Use seus apps do Mac", body: "Funciona com Notas, Excel, Word, PowerPoint, Finder, Contatos, Mensagens e outros, sem sair clicando pela tela. Cada app tem sua própria chave.", example: "Resuma os gastos desta planilha do Excel." },
      { title: "Fale em vez de digitar", body: "Dite com um modelo de voz que roda no seu Mac: você fala e suas palavras aparecem como texto. Na conversa por voz, o Vunemi lê a resposta com a voz do seu Mac, e você pode interrompê-lo falando.", example: "Mostre as reuniões de hoje." },
      { title: "Tarefas agendadas", body: "Peça um resumo toda manhã ou uma checagem semanal. Tarefas agendadas rodam enquanto o Vunemi está aberto e nunca enviam, apagam ou pagam nada.", example: "Toda manhã às 9, resuma minha agenda." },
      { title: "Mostre uma imagem", body: "Anexe uma captura de tela ou foto. Modelos que enxergam imagens a descrevem; com outros modelos, o Vunemi ainda lê o texto dela no seu Mac.", example: "O que significa o erro nesta captura de tela?" },
      { title: "Lembra o que você diz", body: "Diga como você gosta de trabalhar, ou quem é quem, e ele anota com suas próprias palavras depois que você aprova. Cada resposta mostra quais notas recebeu; edite ou apague em Ajustes.", example: "Lembre: quero os relatórios em PDF." },
      { title: "Gravar uma reunião", body: "Clique em Gravar para captar o microfone e o som do Mac. O Vunemi cria a transcrição e o resumo neste Mac; após concluir o resumo, move o áudio para o Lixo. Requer macOS 14.2 ou posterior.", example: "Gravar esta reunião." },
      { title: "Traga trabalho anterior", body: "Digite @ e escolha uma sessão anterior ou uma reunião. As perguntas e respostas dela, ou o resumo da reunião, vão junto com a sua mensagem; até cinco por vez.", example: "Qual hotel escolhemos em @Viagem a Roma?" },
    ],
  },
  screens: {
    title: "Veja em ação",
    intro: "Telas reais do app em inglês, capturadas com dados de exemplo.",
    more: "Todas as telas",
    captions: {
      home: "Comece uma tarefa com suas próprias palavras",
      plan: "Confira o plano antes que algo aconteça",
      browser: "Lê uma página no próprio navegador e responde",
      mention: "Traga uma sessão anterior ou uma reunião para a mensagem com @",
      permissions: "Escolha quando o Vunemi pergunta antes",
      connections: "Toda conexão começa desligada",
      scheduled: "Tarefas agendadas que só leem",
      vault: "As chaves ficam no Cofre; o modelo só vê o nome",
      model: "Escolha um modelo que combine com seu Mac",
    },
  },
  never: {
    title: "O que o Vunemi nunca faz",
    intro: "Em qualquer nível de permissão. Nesses passos ele para e passa o controle para você.",
    items: ["Digitar senhas ou números de cartão, conta ou documento", "Resolver CAPTCHAs", "Pagar qualquer coisa", "Apagar algo para sempre"],
  },
  start: {
    title: "Comece em três passos",
    steps: [
      { title: "Baixe e instale", body: "Abra a imagem de disco e arraste o Vunemi para a pasta Aplicativos." },
      { title: "Escolha um modelo", body: "O Vunemi sugere um modelo adequado à memória do seu Mac e faz o download. Já usa LM Studio ou Ollama? Conecte-o." },
      { title: "Ligue o que precisar", body: "Em Ajustes › Conexões, ligue só o que você quer que o Vunemi use." },
    ],
  },
  notes: {
    title: "Bom saber",
    items: [
      "Os resultados dependem do modelo e do seu Mac. Um modelo pequeno erra mais em tarefas complexas.",
      "Para Macs com Apple Silicon e macOS 14 ou posterior.",
      "As tarefas, inclusive as agendadas, rodam enquanto o Vunemi está aberto.",
      "O app é assinado, mas ainda não foi notarizado pela Apple. Na primeira vez, talvez seja preciso clicar em Abrir Mesmo Assim em Ajustes do Sistema › Privacidade e Segurança.",
    ],
  },
  story: {
    eyebrow: "Por que o Vunemi?",
    title: "As pequenas tarefas se acumulam.",
    body: "Um e-mail esperando resposta, um documento difícil de encontrar, uma agenda cheia. O Vunemi foi feito para esses momentos: cuida das tarefas, pergunta antes de agir e roda a IA no seu Mac.",
  },
  community: {
    title: "Código aberto, feito em conjunto",
    body: "O código do Vunemi está no GitHub sob a licença GPL-3.0. Qualquer pessoa pode lê-lo, conferir o que ele faz e ajudar a melhorá-lo.",
    link: "Vunemi no GitHub",
  },
  featuresPage: {
    title: "Tudo o que o Vunemi faz",
    intro: "O Vunemi 0.1.19 em detalhes: como você trabalha com ele, ao que ele se conecta e como você mantém o controle.",
    chatTitle: "Trabalhando com o Vunemi",
    chat: [
      { title: "Primeiro o plano", body: "Numa tarefa com vários passos, o Vunemi pode mostrar o plano antes. Siga em frente, edite os passos ou cancele." },
      { title: "Cartões de aprovação", body: "Cada mudança chega num cartão que diz o que vai acontecer, onde e para quem." },
      { title: "Fila ou interrupção", body: "Digite o próximo pedido enquanto uma tarefa roda. Ele espera a vez, ou você interrompe para fazê-lo na hora." },
      { title: "Parada de emergência", body: "⌘⇧Esc interrompe uma tarefa em andamento, mesmo com o Vunemi bloqueado." },
      { title: "Continua de onde parou", body: "Se o Vunemi fechar no meio de uma tarefa, ele conta até onde chegou e oferece continuar, perguntando antes de qualquer passo que mude ou envie algo." },
      { title: "Projetos", body: "Transforme uma pasta em projeto: o Vunemi guarda ali os arquivos daquele trabalho, e toda mudança pode ser desfeita." },
      { title: "Memória", body: "Notas com suas próprias palavras, salvas só quando você aprova. Uma tarefa recebe só as notas que servem para ela, e a resposta diz quantas recebeu." },
      { title: "Traga trabalho anterior", body: "Digite @ e escolha uma sessão anterior ou uma reunião. As perguntas e respostas dela, ou o resumo da reunião, vão junto com a sua mensagem; até cinco por vez." },
    ],
    connTitle: "Conexões",
    connIntro: "Cada conexão fica desligada até você ligá-la. Uma conexão desligada é invisível para o modelo: suas ferramentas nem podem ser chamadas. Muitas têm chaves separadas para ler e para alterar.",
    partsLabel: "Chaves",
    connections: [
      { name: "Arquivos", body: "Suas pastas Mesa, Documentos e Downloads, nada além disso.", parts: "Leitura · Gravação (dá para desfazer; o que for apagado vai para o Lixo) · Conversão (imagens, áudio, documentos)" },
      { name: "Navegador", body: "Um navegador dentro da janela do Vunemi, separado do seu Chrome ou Safari. Entre uma vez e continue conectado; assuma o controle quando quiser.", parts: "Leitura de páginas · Cliques e digitação" },
      { name: "Voos e hotéis", body: "Busca no Google Flights e no Trivago e mostra as opções como cartões. Ao escolher um cartão, a oferta abre ao lado do chat. Sua rota ou destino, as datas e o número de viajantes vão para o Google ou o Trivago. O Vunemi não reserva nem paga.", parts: "Google Flights · Trivago" },
      { name: "E-mail", body: "As contas do app Mail do seu Mac (sem senha), Gmail (com senha de app), outras contas IMAP/SMTP e Outlook (com seu próprio ID de aplicativo do Microsoft Entra). O e-mail enviado espera 45 segundos na Caixa de saída. Códigos de uso único e links de acesso nunca são mostrados ao modelo.", parts: "Leitura · Rascunhos · Envio · Organização" },
      { name: "Agenda", body: "As agendas do seu Mac, incluindo as do Google ou Outlook adicionadas em Contas de Internet. Ele não pode convidar ninguém.", parts: "Leitura · Criar e alterar (dá para desfazer)" },
      { name: "Lembretes", body: "Os lembretes do seu Mac.", parts: "Leitura · Criar e alterar (dá para desfazer)" },
      { name: "Apps do Mac", body: "Notas, Finder, Word, Excel, PowerPoint, Música, Fotos, Safari, Chrome, Contatos, Mensagens e outros apps com suporte a scripts, sem clicar na tela.", parts: "Uma chave por app" },
      { name: "Atalhos", body: "Lista seus Atalhos da Apple e executa o que você pedir.", parts: "Pergunta antes de cada execução" },
      { name: "Área de trabalho", body: "Lê janelas de apps e, se você permitir, clica e digita. Terminal, gerenciadores de senhas e Ajustes do Sistema ficam sempre de fora.", parts: "Leitura · Controle" },
      { name: "Tarefas agendadas", body: "Tarefas criadas no chat que rodam em horários fixos enquanto o Vunemi está aberto. Nunca enviam, apagam ou pagam nada.", parts: "Criação e gerenciamento" },
      { name: "Histórico", body: "Encontra suas sessões anteriores e reuniões gravadas quando um pedido trata de uma delas. Cada pedido leva apenas o nome, a data e uma linha das poucas que se encaixam; o Vunemi só lê uma quando precisa. Nada sai do seu Mac.", parts: "Buscar e ler" },
      { name: "Suas próprias conexões", body: "Adicione qualquer servidor MCP por comando ou endereço. As chaves dele ficam no Cofre.", parts: "Uma chave por conexão" },
    ],
    safetyTitle: "Segurança e controle",
    safety: [
      { title: "Níveis de permissão", body: "Quatro predefinições, de Observar e sugerir a Agir sozinho, além de um ajuste para cada tipo de ação. Ações financeiras ficam sempre desligadas." },
      { title: "Cofre", body: "As chaves usadas pelas ferramentas são criptografadas com uma chave das Chaves do seu Mac. O modelo só vê o nome." },
      { title: "Registro de atividades", body: "Tudo o que o assistente fez, guardado no seu Mac, com Desfazer." },
      { title: "Feito pelo Vunemi", body: "Arquivos que ele gravou, rascunhos que salvou, eventos que criou e arquivos que baixou, com Abrir e Mostrar no Finder." },
      { title: "Caixa de saída", body: "Mensagens esperando envio e o que aconteceu com cada uma." },
      { title: "Bloqueio do app", body: "Bloqueie o Vunemi com o Touch ID ou a senha do Mac." },
      { title: "Seus dados, sua decisão", body: "Esqueça uma sessão, uma nota ou tudo. Uma nota da memória nunca concede permissão, e palavras de páginas, e-mails ou arquivos nunca viram uma nota." },
    ],
    extras: [
      { title: "Roda no seu Mac", body: "Use o motor integrado do Vunemi ou um servidor de modelos que você já tem: LM Studio, Ollama ou llama.cpp. Também dá para adicionar um arquivo GGUF do seu Mac." },
      { title: "11 idiomas", body: "Português, inglês, turco, alemão, francês, espanhol, italiano, russo, chinês, japonês e coreano." },
    ],
  },
  screensPage: {
    title: "Telas do Vunemi",
    intro: "Telas reais do app em inglês, capturadas com dados de exemplo. Abra qualquer imagem para ver em tamanho real.",
  },
  downloadPage: {
    highlightsTitle: "Novidades desta versão",
    highlights: [
      "Calendário: se duas das suas contas têm um calendário ou uma lista de lembretes com o mesmo nome, o Vunemi pergunta qual antes de adicionar qualquer coisa. Um evento ou lembrete que você restaura depois de apagar volta para o calendário de onde veio. Conexões agora mostra as contas de onde vêm seus calendários.",
      "Se o arquivo que guarda suas automações estiver danificado, o Vunemi abre mesmo assim: deixa o arquivo de lado e começa com a lista vazia.",
      "Os arquivos de áudio que sobram de uma conversa por voz são apagados na próxima vez que o Vunemi fala. O app agora roda no Electron 44.",
    ],
    title: "Baixe o Vunemi",
    intro: "Gratuito e de código aberto. Para Macs com Apple Silicon e macOS 14 ou posterior.",
    requirementsTitle: "Você precisa de",
    requirements: ["Um Mac com Apple Silicon (M1 ou posterior)", "macOS 14 ou posterior", "Espaço para um modelo: o app mostra o tamanho de cada modelo antes do download"],
    installTitle: "Instalação",
    install: [
      "Abra a imagem de disco que você baixou.",
      "Arraste o Vunemi para a pasta Aplicativos.",
      "Abra o Vunemi em Aplicativos. Se o macOS disser que ele não pode ser aberto, vá em Ajustes do Sistema › Privacidade e Segurança e clique em Abrir Mesmo Assim.",
      "Escolha um modelo na primeira tela. O Vunemi sugere um adequado ao seu Mac.",
    ],
    updateTitle: "Atualização",
    updateBody: "A partir da 0.1.8, o Vunemi avisa quando sai uma versão nova e se atualiza quando você toca em Atualizar. Numa versão mais antiga, baixe uma vez a nova imagem de disco e arraste o Vunemi para Aplicativos, escolhendo Substituir.",
    checksum: "SHA-256",
    notes: "Notas da versão",
    source: "Código-fonte",
    guide: "Guia",
  },
};
