export default {
  langName: "Türkçe",
  nav: { home: "Ana sayfa", features: "Neler yapar?", screens: "Ekranlar", download: "İndir", guide: "Rehber" },
  language: "Dil",
  skip: "İçeriğe geç",
  footer: "Bu sitede çerez veya izleme kodu yok.",
  demo: {
      "user": "Masaüstündeki faturaları bul ve tek klasörde topla.",
      "planTitle": "Planı onayla",
      "steps": [
          "Masaüstünde faturaları ara",
          "Faturalar adında bir klasör oluştur",
          "Faturaları içine taşı"
      ],
      "go": "Devam et",
      "edit": "Düzenle",
      "cancel": "İptal",
      "cardTitle": "4 dosyayı taşı",
      "cardBody": "Masaüstü → Belgeler/Faturalar",
      "approve": "Onayla",
      "deny": "Reddet",
      "done": "Tamam. 4 fatura Belgeler/Faturalar klasöründe.",
      "logItem": "4 dosya Faturalar'a taşındı",
      "undo": "Geri al",
      "model": "Yerel model",
      "localNote": "Yapay zekâ modeli bu Mac'te çalışır.",
      "noCloud": "Vunemi bulutunda işlenmez"
  },
  meta: {
    home: { title: "Vunemi: Mac'inde çalışan kişisel asistan", description: "Vunemi günlük işlerde yardımcı olur. Yapay zekâ Mac'inde çalışır; Vunemi bulut hesabı gerekmez. Hangi dış hizmetlere bağlanacağını sen seçersin." },
    features: { title: "Vunemi neler yapar?", description: "E-posta, takvim, dosyalar, web ve Mac uygulamaların; onay kartları, geri alma ve kesin sınırlarla. Vunemi 0.1.17'in yapabildiği her şey." },
    screens: { title: "Vunemi ekranları", description: "Mac için Vunemi uygulamasından, örnek verilerle çekilmiş gerçek ekranlar." },
    download: { title: "Vunemi'yi Mac için indir", description: "Vunemi 0.1.17'i Apple Silicon ve macOS 14 veya sonrası için indir. Ücretsiz ve açık kaynak." },
  },
  hero: {
    eyebrow: "Mac için kişisel asistan",
    title: "Günlük işlerde yardım. Yapay zekâ Mac'inde çalışır.",
    lead: "Vunemi e-posta, dosya, takvim ve web işlerinde sana yardım eder. Bir şeyi değiştirmeden önce sorar. Model Mac'inde çalışır; sohbetlerini ve belgelerini işlemek için Vunemi'nin sunucularına yüklemez.",
    download: "Mac için indir",
    explore: "Neler yaptığını gör",
    facts: ["Ücretsiz ve açık kaynak", "Apple Silicon", "macOS 14 veya sonrası"],
    caption: "Vunemi planını gösterir ve seni bekler",
  },
  strengths: {
    title: "Vunemi'yi farklı kılan ne?",
    items: [
      { title: "Yapay zekâ Mac'inde çalışır", body: "Vunemi hesabı veya aboneliği gerekmez. Model görevleri Mac'inde işler. Gmail, Outlook veya web sitelerine bağlanırsan bu hizmetler görev için gereken verileri alır; bunlar Vunemi'nin bulut hizmetleri değildir." },
      { title: "Son söz sende", body: "Her bağlantı kapalı başlar. Bir şey değişmeden önce Vunemi ne yapacağını açıkça yazan bir kart gösterir ve seni bekler. Ne sıklıkla soracağını sen seçersin." },
      { title: "Hatalar geri alınabilir", body: "Vunemi'nin yaptığı her şey Etkinlik günlüğünde Geri al düğmesiyle listelenir. Silinen dosyalar Çöp'e gider; gönderilen e-posta 45 saniye bekler, istersen geri alırsın." },
    ],
  },
  features: {
    title: "Nelerde yardım eder?",
    intro: "Kendi kelimelerinle iste. Sadece ihtiyacın olan bağlantıları aç.",
    more: "Tüm özellikler",
    cards: [
      { title: "E-postaları takip et", body: "Yanıt bekleyen e-postaları bulur, yazışmaları özetler ve taslak yazar. Mac'teki Mail uygulamasındaki hesaplarla, Gmail, Outlook ve diğer IMAP hesaplarıyla çalışır; onayın olmadan asla göndermez.", example: "Hangi e-postalar yanıtımı bekliyor?" },
      { title: "Gününü planla", body: "Mac'ine eklediğin Google veya Outlook takvimleri dahil takvimlerini ve anımsatıcılarını okur; onaylarsan etkinlik ya da yapılacak iş ekler.", example: "Yarın takvimimde neler var?" },
      { title: "Dosyaları bul ve düzenle", body: "Masaüstü, Belgeler ve İndirilenler'de arar, belgeleri okur, onayından sonra dosyaları taşır veya yeniden adlandırır. Her değişiklik geri alınabilir.", example: "Masaüstündeki faturaları bul ve tek klasörde topla." },
      { title: "Web'de araştır", body: "Sayfaları kendi tarayıcından ayrı, Vunemi'nin içindeki bir tarayıcıda açar. Okur, karşılaştırır, form doldurur; istediğin an Kontrolü al düğmesine basabilirsin.", example: "Bu üç müzenin açılış saatlerini karşılaştır." },
      { title: "Mac uygulamalarını kullan", body: "Notlar, Excel, Word, PowerPoint, Finder, Kişiler, Mesajlar ve daha fazlasıyla, ekranda tıklamadan çalışır. Her uygulamanın kendi anahtarı var.", example: "Bu Excel tablosundaki giderleri özetle." },
      { title: "Yazmak yerine konuş", body: "Mac'inde çalışan bir konuşma modeliyle dikte et: sen konuşursun, sözlerin yazıya dönüşür. Sesli yanıt veren sesli sohbet sonraki sürümlerde gelecek.", example: "Bugünkü toplantılarımı göster." },
      { title: "İşleri zamanla", body: "Sabah özeti ya da haftalık bir kontrol iste. Zamanlanmış işler Vunemi açıkken çalışır; asla gönderim, silme veya ödeme yapmaz.", example: "Her sabah 9'da takvimimi özetle." },
      { title: "Bir resim göster", body: "Ekran görüntüsü veya fotoğraf ekle. Görsel görebilen modeller onu anlatır; diğer modellerde de Vunemi içindeki yazıyı Mac'inde okur.", example: "Bu ekran görüntüsündeki hata ne anlama geliyor?" },
      { title: "Söylediklerini hatırlar", body: "Nasıl çalışmayı sevdiğini ya da kimin kim olduğunu söyle; onay verdiğinde bunu kendi sözlerinle not eder. Her yanıt hangi notların verildiğini gösterir; notları Ayarlar'da düzenleyip silebilirsin.", example: "Hatırla: raporları PDF olarak isterim." },
      { title: "Toplantıyı kaydet", body: "Kaydet düğmesi mikrofonunu ve Mac sesini kaydeder. Vunemi dökümü ve özeti bu Mac’te oluşturur; özet başarıyla tamamlanınca ses dosyalarını Çöp’e taşır. macOS 14.2 veya sonrası gerekir.", example: "Bu toplantıyı kaydet." },
      { title: "Önceki işi getir", body: "@ yazıp önceki bir oturumu ya da toplantıyı seç. Oturumun soruları ve yanıtları ya da toplantının özeti mesajınla birlikte gider; bir mesaja en çok beş tane.", example: "@Roma gezisi'nde hangi oteli seçmiştik?" },
    ],
  },
  screens: {
    title: "İş başında gör",
    intro: "İngilizce uygulamadan, örnek verilerle çekilmiş gerçek ekranlar.",
    more: "Tüm ekranlar",
    captions: {
      home: "Bir görevi kendi kelimelerinle başlat",
      plan: "Bir şey olmadan önce planı gör",
      browser: "Kendi tarayıcısında bir sayfayı okur ve yanıtlar",
      mention: "@ ile önceki bir oturumu ya da toplantıyı mesaja getir",
      permissions: "Vunemi'nin ne zaman önce soracağını seç",
      connections: "Her bağlantı kapalı başlar",
      scheduled: "Sadece okuyan zamanlanmış işler",
      vault: "Anahtarlar Kasa'da kalır; model yalnızca adını görür",
      model: "Mac'ine uygun bir model seç",
    },
  },
  never: {
    title: "Vunemi'nin asla yapmadıkları",
    intro: "Hangi izin seviyesinde olursa olsun. Bu adımlarda durur ve sözü sana bırakır.",
    items: ["Parola, kart, banka veya kimlik numarası yazmak", "CAPTCHA çözmek", "Herhangi bir ödeme yapmak", "Bir şeyi kalıcı olarak silmek"],
  },
  start: {
    title: "Üç adımda başla",
    steps: [
      { title: "İndir ve kur", body: "Disk görüntüsünü aç ve Vunemi'yi Uygulamalar klasörüne sürükle." },
      { title: "Bir model seç", body: "Vunemi, Mac'inin belleğine uygun bir model önerir ve indirir. LM Studio veya Ollama kullanıyorsan onu bağlayabilirsin." },
      { title: "Gerekeni aç", body: "Ayarlar › Bağlantılar'da yalnızca Vunemi'nin kullanmasını istediklerini aç." },
    ],
  },
  notes: {
    title: "Bilmekte fayda var",
    items: [
      "Sonuçlar modele ve Mac'ine göre değişir. Küçük bir model karmaşık işlerde daha çok hata yapar.",
      "Apple Silicon ve macOS 14 veya sonrası olan Mac'ler için.",
      "Zamanlanmış olanlar dahil görevler, Vunemi açıkken çalışır.",
      "Uygulama imzalı ama henüz Apple tarafından noterlenmedi. İlk açılışta Sistem Ayarları › Gizlilik ve Güvenlik'te Yine de Aç'a basman gerekebilir.",
    ],
  },
  story: {
    eyebrow: "Neden Vunemi?",
    title: "Küçük işler birikir.",
    body: "Yanıt bekleyen bir e-posta, bulamadığın bir belge, kalabalık bir takvim. Vunemi tam bu anlar için yapıldı: ayak işini üstlenir, adım atmadan önce sorar ve yapay zekâyı Mac'inde çalıştırır.",
  },
  community: {
    title: "Açık kaynak, birlikte geliştiriliyor",
    body: "Vunemi'nin kodu GPL-3.0 lisansıyla GitHub'da. Herkes okuyabilir, ne yaptığını kontrol edebilir ve daha iyi olmasına katkı verebilir.",
    link: "GitHub'da Vunemi",
  },
  featuresPage: {
    title: "Vunemi'nin yapabildiği her şey",
    intro: "Ayrıntılarıyla Vunemi 0.1.17: onunla nasıl çalışırsın, nelere bağlanabilir ve kontrol nasıl sende kalır.",
    chatTitle: "Vunemi ile çalışmak",
    chat: [
      { title: "Önce plan", body: "Birkaç adımlı bir işte Vunemi önce planı gösterebilir. Devam et, adımları düzenle ya da iptal et." },
      { title: "Onay kartları", body: "Her değişiklik; ne olacağını, nerede ve kime yapılacağını yazan bir kartla gelir." },
      { title: "Sıraya koy ya da araya gir", body: "Bir görev sürerken sıradaki isteğini yaz. Sırasını bekler ya da araya girip hemen yaptırırsın." },
      { title: "Acil durdurma", body: "⌘⇧Esc çalışan görevi durdurur; Vunemi kilitliyken bile." },
      { title: "Kaldığı yerden devam", body: "Vunemi bir görevin ortasında kapanırsa nereye kadar geldiğini söyler ve devam etmeyi önerir; değiştiren veya gönderen her adımdan önce sorar." },
      { title: "Projeler", body: "Bir klasörü proje yap: Vunemi o işin dosyalarını orada tutar ve her değişiklik geri alınabilir." },
      { title: "Hafıza", body: "Senin sözlerinden notlar; yalnız onay verdiğinde kaydedilir. Bir göreve yalnız ona uyan notlar verilir ve yanıt kaç not verildiğini söyler." },
      { title: "Önceki işi getir", body: "@ yazıp önceki bir oturumu ya da toplantıyı seç. Oturumun soruları ve yanıtları ya da toplantının özeti mesajınla birlikte gider; bir mesaja en çok beş tane." },
    ],
    connTitle: "Bağlantılar",
    connIntro: "Her bağlantı sen açana kadar kapalıdır. Kapalı bir bağlantı modele görünmez; araçları hiç çağrılamaz. Birçoğunda okuma ve değiştirme için ayrı anahtarlar var.",
    partsLabel: "Anahtarlar",
    connections: [
      { name: "Dosyalar", body: "Masaüstü, Belgeler ve İndirilenler klasörlerin; başka hiçbir yer.", parts: "Okuma · Yazma (geri alınabilir; silinenler Çöp'e gider) · Dönüştürme (resim, ses, belge)" },
      { name: "Tarayıcı", body: "Chrome veya Safari'nden ayrı, Vunemi penceresindeki bir tarayıcı. Bir kez giriş yap, oturumun açık kalsın; istediğin an Kontrolü al.", parts: "Sayfa okuma · Tıklama ve yazma" },
      { name: "Uçuş ve otel", body: "Google Flights ve Trivago'da arar, seçenekleri kart olarak gösterir. Bir kartı seçince teklifi sohbetin yanında açılır. Rotan ya da gideceğin yer, tarihler ve kişi sayısı Google'a ya da Trivago'ya gider. Vunemi rezervasyon ya da ödeme yapmaz.", parts: "Google Flights · Trivago" },
      { name: "E-posta", body: "Mac'teki Mail uygulamasındaki hesaplar (parola gerekmez), Gmail (uygulama şifresiyle), diğer IMAP/SMTP hesapları ve Outlook (kendi Microsoft Entra uygulama kimliğinle). Giden e-posta Giden Kutusu'nda 45 saniye bekler. Tek kullanımlık kodlar ve giriş bağlantıları modele asla gösterilmez.", parts: "Okuma · Taslak · Gönderme · Düzenleme" },
      { name: "Takvim", body: "İnternet Hesapları'na eklediğin Google veya Outlook takvimleri dahil Mac'indeki takvimler. Kimseyi davet edemez.", parts: "Okuma · Ekleme ve değiştirme (geri alınabilir)" },
      { name: "Anımsatıcılar", body: "Mac'indeki anımsatıcılar.", parts: "Okuma · Ekleme ve değiştirme (geri alınabilir)" },
      { name: "Mac uygulamaları", body: "Notlar, Finder, Word, Excel, PowerPoint, Müzik, Fotoğraflar, Safari, Chrome, Kişiler, Mesajlar ve betik destekleyen diğer uygulamalar; ekrana tıklamadan.", parts: "Her uygulama için ayrı anahtar" },
      { name: "Kestirmeler", body: "Apple Kestirmeler'ini listeler ve istediğini çalıştırır.", parts: "Her çalıştırmadan önce sorar" },
      { name: "Masaüstü", body: "Uygulama pencerelerini okur ve izin verirsen tıklar, yazar. Terminal, parola yöneticileri ve Sistem Ayarları her zaman yasaktır.", parts: "Okuma · Kontrol" },
      { name: "Zamanlanmış işler", body: "Sohbette kurduğun, Vunemi açıkken belirli saatlerde çalışan işler. Asla gönderim, silme veya ödeme yapmaz.", parts: "Kurma ve yönetme" },
      { name: "Geçmiş", body: "Bir istek eski bir oturumla ya da kayıtlı bir toplantıyla ilgiliyse onu bulur. Her istekle yalnız en uygun birkaçının adı, tarihi ve tek satırı gider; Vunemi gerekirse birini okur. Hiçbir şey Mac'inden çıkmaz.", parts: "Bulma ve okuma" },
      { name: "Kendi bağlantıların", body: "Komutla veya adresle istediğin MCP sunucusunu ekle. Anahtarları Kasa'da tutulur.", parts: "Her bağlantı için ayrı anahtar" },
    ],
    safetyTitle: "Güvenlik ve kontrol",
    safety: [
      { title: "İzin seviyeleri", body: "İzle ve öner'den Kendi başına yap'a dört hazır ayar, ayrıca her işlem türü için ayrı seçim. Parayla ilgili işlemler her zaman kapalı." },
      { title: "Kasa", body: "Araçların kullandığı anahtarlar, Mac'inin Anahtar Zinciri'ndeki bir anahtarla şifrelenir. Model yalnızca adını görür." },
      { title: "Etkinlik günlüğü", body: "Asistanın yaptığı her şey, Mac'inde, Geri al düğmesiyle." },
      { title: "Vunemi'nin yaptıkları", body: "Yazdığı dosyalar, kaydettiği taslaklar, eklediği etkinlikler ve indirdiği dosyalar; Aç ve Finder'da Göster ile." },
      { title: "Giden Kutusu", body: "Gönderilmeyi bekleyen mesajlar ve her birine ne olduğu." },
      { title: "Uygulama kilidi", body: "Vunemi'yi Touch ID veya Mac parolanla kilitle." },
      { title: "Verin, kararın", body: "Bir oturumu, bir notu ya da her şeyi unut. Hafızadaki bir not hiçbir izin vermez; sayfalardan, e-postalardan ya da dosyalardan gelen sözler asla not olamaz." },
    ],
    extras: [
      { title: "Mac'inde çalışır", body: "Vunemi'nin yerleşik motorunu ya da zaten kullandığın bir model sunucusunu seç: LM Studio, Ollama veya llama.cpp. Mac'indeki bir GGUF dosyasını da ekleyebilirsin." },
      { title: "11 dil", body: "Türkçe, İngilizce, Almanca, Fransızca, İspanyolca, İtalyanca, Portekizce, Rusça, Çince, Japonca ve Korece." },
    ],
  },
  screensPage: {
    title: "Vunemi ekranları",
    intro: "İngilizce uygulamadan, örnek verilerle çekilmiş gerçek ekranlar. Tam boyut görmek için bir görüntüyü aç.",
  },
  downloadPage: {
    title: "Vunemi'yi indir",
    intro: "Ücretsiz ve açık kaynak. Apple Silicon ve macOS 14 veya sonrası olan Mac'ler için.",
    highlightsTitle: "Bu sürümde neler yeni?",
    highlights: [
      "Yeni bağlantı: Geçmiş. Açıkken Vunemi, bir istek eski bir oturumla ya da kayıtlı bir toplantıyla ilgiliyse onu bulur ve gerekeni okur. Sen Ayarlar › Bağlantılar'dan açana kadar kapalıdır.",
      "Vunemi artık bir sayfanın başka bir siteden gömdüğü içeriği de okur ve orada çalışır: harita ya da rezervasyon formu gibi. CAPTCHA ve reklam çerçeveleri ona kapalıdır.",
      "Web sitelerindeki giriş, parola, kart ve kişisel bilgi alanlarına yazmayı artık uygulamanın kendisi reddeder; Vunemi bunları sana bırakır.",
      "Vunemi'nin görev sırasında görmeden yazdığı bağlantılar “doğrulanmadı” diye işaretlenir.",
      "İki kez yazılan cevap bir kez gösterilir; başlıklar altında yazılan seçenekler karta dönüşür.",
    ],
    requirementsTitle: "Gerekenler",
    requirements: ["Apple Silicon'lu bir Mac (M1 veya sonrası)", "macOS 14 veya sonrası", "Model için yer: uygulama her modelin boyutunu indirmeden önce gösterir"],
    installTitle: "Kurulum",
    install: [
      "İndirdiğin disk görüntüsünü aç.",
      "Vunemi'yi Uygulamalar klasörüne sürükle.",
      "Vunemi'yi Uygulamalar'dan aç. macOS açılamayacağını söylerse Sistem Ayarları › Gizlilik ve Güvenlik'e git ve Yine de Aç'a bas.",
      "İlk ekranda bir model seç. Vunemi Mac'ine uygun olanı önerir.",
    ],
    updateTitle: "Güncelleme",
    updateBody: "0.1.8'den itibaren Vunemi yeni sürüm çıktığında haber verir ve Güncelle'ye basınca kendini günceller. Daha eski bir sürümden, yeni disk görüntüsünü bir kez indirip Vunemi'yi Uygulamalar'a sürükle ve Değiştir'i seç.",
    checksum: "SHA-256",
    notes: "Sürüm notları",
    source: "Kaynak kod",
    guide: "Rehber",
  },
};
