export default {
  langName: "中文",
  nav: { home: "首页", features: "功能", screens: "应用画面", download: "下载", guide: "指南" },
  language: "语言",
  skip: "跳到正文",
  footer: "本网站不使用 Cookie 或跟踪脚本。",
  demo: {
      "user": "找出桌面上的发票，放到一个文件夹里。",
      "planTitle": "确认计划",
      "steps": [
          "在桌面上查找发票",
          "新建名为“发票”的文件夹",
          "把发票移进去"
      ],
      "go": "开始",
      "edit": "编辑",
      "cancel": "取消",
      "cardTitle": "移动 4 个文件",
      "cardBody": "桌面 → 文稿/发票",
      "approve": "批准",
      "deny": "拒绝",
      "done": "完成。4 张发票已放在“文稿/发票”中。",
      "logItem": "已将 4 个文件移到“发票”",
      "undo": "撤销",
      "model": "本地模型",
      "localNote": "AI 模型在这台 Mac 上运行。",
      "noCloud": "不在 Vunemi 云端处理"
  },
  meta: {
    home: { title: "Vunemi：在你的 Mac 上运行的个人助理", description: "Vunemi 帮你处理日常事务。AI 在你的 Mac 上运行，无需 Vunemi 云账号；由你选择要连接的外部服务。" },
    features: { title: "Vunemi 能做什么", description: "邮件、日历、文件、网页和 Mac 应用，配有确认卡片、撤销功能和明确的限制。Vunemi 0.1.18 的全部功能。" },
    screens: { title: "Vunemi 应用画面", description: "Mac 版 Vunemi 的真实画面，使用示例数据截取。" },
    download: { title: "下载 Mac 版 Vunemi", description: "下载 Vunemi 0.1.18，适用于搭载 Apple 芯片、运行 macOS 14 或更高版本的 Mac。免费且开源。" },
  },
  hero: {
    eyebrow: "Mac 上的个人助理",
    title: "帮你处理日常事务，AI 在你的 Mac 上运行。",
    lead: "Vunemi 帮你处理邮件、文件、日历和网页。修改内容前，它会先征求你的同意。AI 模型在你的 Mac 上运行；Vunemi 不会把对话或文档上传到自己的云端处理。",
    download: "下载 Mac 版",
    explore: "看看它能做什么",
    facts: ["免费且开源", "Apple 芯片", "macOS 14 或更高版本"],
    caption: "Vunemi 先给出计划，等你决定",
  },
  strengths: {
    title: "Vunemi 有什么不同",
    items: [
      { title: "AI 在你的 Mac 上运行", body: "无需 Vunemi 账号或订阅。AI 模型在你的 Mac 上处理任务。若你连接 Gmail、Outlook 或网站，这些服务会交换完成任务所需的数据；它们不是 Vunemi 的云服务。" },
      { title: "最终决定权在你", body: "所有连接默认关闭。改动任何内容前，Vunemi 会显示一张卡片，写明它要做什么，然后等你确认。多久问你一次，由你决定。" },
      { title: "出错可以撤销", body: "Vunemi 做过的每件事都会记录在活动日志中，并附有“撤销”按钮。删除的文件会进入废纸篓，发出的邮件会等待 45 秒，让你有机会收回。" },
    ],
  },
  features: {
    title: "它能帮你做什么",
    intro: "用你自己的话提出要求。只打开你需要的连接。",
    more: "全部功能",
    cards: [
      { title: "轻松处理邮件", body: "找出等你回复的邮件，总结往来内容，并起草回复。支持 Mac 上“邮件”App 中的账户、Gmail、Outlook 和其他 IMAP 账户，未经你同意绝不发送。", example: "哪些邮件在等我回复？" },
      { title: "安排好一天", body: "读取你的日历和提醒事项，包括添加到 Mac 上的 Google 或 Outlook 日历，经你同意后添加日程或待办。", example: "我明天的日程有哪些？" },
      { title: "查找和整理文件", body: "在桌面、文稿和下载文件夹中搜索，阅读文档，经你同意后移动或重命名文件。每项改动都可以撤销。", example: "找出桌面上的发票，放到一个文件夹里。" },
      { title: "上网查资料", body: "在 Vunemi 内置的浏览器中打开网页，与你自己的浏览器分开。它会阅读、比较、填写表单，你随时可以点“接管控制”。", example: "比较这三家博物馆的开放时间。" },
      { title: "使用 Mac 应用", body: "可配合备忘录、Excel、Word、PowerPoint、访达、通讯录、信息等应用工作，无需在屏幕上到处点击。每个应用都有单独的开关。", example: "汇总这张 Excel 表里的支出。" },
      { title: "说话代替打字", body: "用在 Mac 上运行的语音模型听写：你说话，文字就会出现。在语音对话中，Vunemi 会用 Mac 自带的声音朗读回答，你可以随时开口打断。", example: "给我看看今天的会议。" },
      { title: "定时任务", body: "让它每天早上做一份汇总，或每周检查一次。定时任务在 Vunemi 打开时运行，绝不会发送、删除或付款。", example: "每天早上 9 点汇总我的日历。" },
      { title: "给它看图片", body: "附上截图或照片。能看懂图片的模型会描述内容；换成其他模型，Vunemi 也能在你的 Mac 上读出图中的文字。", example: "这张截图里的错误是什么意思？" },
      { title: "记住你说过的话", body: "告诉它你喜欢的工作方式，或谁是谁；经你同意后，它会用你的原话记下来。每个回答都会显示它收到了哪些笔记；你可以在设置中编辑或删除。", example: "记住：我要 PDF 格式的报告。" },
      { title: "录制会议", body: "点击“录制”以采集麦克风和 Mac 声音。Vunemi 在此 Mac 上生成文字记录和摘要；摘要完成后将音频移入废纸篓。需要 macOS 14.2 或更高版本。", example: "录制这场会议。" },
      { title: "带入之前的工作", body: "输入 @，选择之前的会话或会议。其中的提问和回答，或会议的摘要，会随消息一起发送；每条消息最多五个。", example: "我们在 @罗马之行 里选了哪家酒店？" },
    ],
  },
  screens: {
    title: "看看它如何工作",
    intro: "英文版应用的真实画面，使用示例数据截取。",
    more: "全部画面",
    captions: {
      home: "用你自己的话开始一项任务",
      plan: "在任何操作发生前先查看计划",
      browser: "在自己的浏览器中阅读网页并回答",
      mention: "用 @ 把之前的会话或会议带入消息",
      permissions: "选择 Vunemi 何时需要先问你",
      connections: "所有连接默认关闭",
      scheduled: "只读的定时任务",
      vault: "密钥保存在保险库中，模型只能看到名称",
      model: "选择适合你 Mac 的模型",
    },
  },
  never: {
    title: "Vunemi 绝不会做的事",
    intro: "无论权限级别如何。遇到这些步骤，它都会停下来交给你。",
    items: ["输入密码、银行卡号、账号或证件号码", "破解验证码（CAPTCHA）", "支付任何款项", "永久删除任何内容"],
  },
  start: {
    title: "三步开始使用",
    steps: [
      { title: "下载并安装", body: "打开磁盘映像，把 Vunemi 拖到“应用程序”文件夹。" },
      { title: "选择模型", body: "Vunemi 会推荐适合你 Mac 内存的模型并自动下载。已经在用 LM Studio 或 Ollama？直接连接即可。" },
      { title: "只打开需要的", body: "在“设置 › 连接”中，只打开你希望 Vunemi 使用的项目。" },
    ],
  },
  notes: {
    title: "须知",
    items: [
      "效果取决于模型和你的 Mac。小模型在复杂任务上更容易出错。",
      "适用于搭载 Apple 芯片、运行 macOS 14 或更高版本的 Mac。",
      "任务（包括定时任务）只在 Vunemi 打开时运行。",
      "应用已签名，但尚未经过 Apple 公证。首次打开时，你可能需要在“系统设置 › 隐私与安全性”中点按“仍要打开”。",
    ],
  },
  story: {
    eyebrow: "为什么是 Vunemi？",
    title: "小事会越积越多。",
    body: "一封待回复的邮件，一份找不到的文件，一张排满的日历。Vunemi 正是为这些时刻而做：它分担琐事，操作前先询问，并在你的 Mac 上运行 AI。",
  },
  community: {
    title: "开源，共同打造",
    body: "Vunemi 的代码以 GPL-3.0 许可证发布在 GitHub 上。任何人都可以阅读代码、核实它在做什么，并帮助改进。",
    link: "GitHub 上的 Vunemi",
  },
  featuresPage: {
    title: "Vunemi 的全部功能",
    intro: "详细了解 Vunemi 0.1.18：如何与它协作、它能连接什么，以及你如何保持掌控。",
    chatTitle: "与 Vunemi 协作",
    chat: [
      { title: "先看计划", body: "遇到需要多个步骤的任务，Vunemi 可以先给出计划。你可以开始执行、编辑步骤或取消。" },
      { title: "确认卡片", body: "每项改动都会以卡片形式呈现，写明会发生什么、在哪里、涉及谁。" },
      { title: "排队或插队", body: "任务运行时可以输入下一个请求。它会排队等候，你也可以中断当前任务，让它马上执行。" },
      { title: "紧急停止", body: "按 ⌘⇧Esc 可停止正在运行的任务，即使 Vunemi 已锁定也有效。" },
      { title: "从中断处继续", body: "如果 Vunemi 在任务中途关闭，它会告诉你进行到哪一步并提议继续；遇到会改动或发送内容的步骤，都会先问你。" },
      { title: "项目", body: "把一个文件夹设为项目：Vunemi 会把这项工作的文件放在那里，每项改动都可以撤销。" },
      { title: "记忆", body: "来自你原话的笔记，只有经你同意才会保存。每个任务只会收到与之相关的笔记，回答会说明收到了几条。" },
      { title: "带入之前的工作", body: "输入 @，选择之前的会话或会议。其中的提问和回答，或会议的摘要，会随消息一起发送；每条消息最多五个。" },
    ],
    connTitle: "连接",
    connIntro: "每个连接在你打开之前都是关闭的。关闭的连接对模型不可见，其工具根本无法调用。很多连接对“读取”和“修改”设有单独的开关。",
    partsLabel: "开关",
    connections: [
      { name: "文件", body: "只限你的桌面、文稿和下载文件夹。", parts: "读取 · 写入（可撤销；删除的内容进入废纸篓）· 转换（图片、音频、文档）" },
      { name: "浏览器", body: "Vunemi 窗口中的浏览器，与你的 Chrome 或 Safari 分开。登录一次即可保持登录；随时可以接管控制。", parts: "读取网页 · 点击和输入" },
      { name: "航班和酒店", body: "在 Google Flights 和 Trivago 搜索，并以卡片展示结果。选择一张卡片即可在对话旁打开对应报价。你的航线或目的地、日期和人数会发送给 Google 或 Trivago。Vunemi 不会预订或付款。", parts: "Google Flights · Trivago" },
      { name: "邮件", body: "Mac 上“邮件”App 中的账户（无需密码）、Gmail（使用应用专用密码）、其他 IMAP/SMTP 账户，以及 Outlook（使用你自己的 Microsoft Entra 应用 ID）。发出的邮件会在发件箱等待 45 秒。一次性验证码和登录链接绝不会显示给模型。", parts: "读取 · 草稿 · 发送 · 整理" },
      { name: "日历", body: "你 Mac 上的日历，包括在“互联网账户”中添加的 Google 或 Outlook 日历。它无法邀请任何人。", parts: "读取 · 添加和修改（可撤销）" },
      { name: "提醒事项", body: "你 Mac 上的提醒事项。", parts: "读取 · 添加和修改（可撤销）" },
      { name: "Mac 应用", body: "备忘录、访达、Word、Excel、PowerPoint、音乐、照片、Safari、Chrome、通讯录、信息以及其他支持脚本的应用，无需点击屏幕。", parts: "每个应用一个开关" },
      { name: "快捷指令", body: "列出你的 Apple 快捷指令，并运行你指定的那一个。", parts: "每次运行前都会询问" },
      { name: "桌面", body: "读取应用窗口，经你允许后可以点击和输入。终端、密码管理器和系统设置始终禁止操作。", parts: "读取 · 控制" },
      { name: "定时任务", body: "在对话中设置、在 Vunemi 打开时按时运行的任务。绝不会发送、删除或付款。", parts: "设置与管理" },
      { name: "历史记录", body: "当请求涉及以前的会话或已录制的会议时找到它。每次请求只附上最相关的几项的名称、日期和一行说明；Vunemi 只在需要时阅读其中一项。任何内容都不会离开你的 Mac。", parts: "查找和阅读" },
      { name: "自定义连接", body: "通过命令或地址添加任意 MCP 服务器。它的密钥保存在保险库中。", parts: "每个连接一个开关" },
    ],
    safetyTitle: "安全与掌控",
    safety: [
      { title: "权限级别", body: "从“观察并建议”到“自主执行”共四种预设，另外还可按操作类型分别设置。涉及资金的操作始终关闭。" },
      { title: "保险库", body: "工具使用的密钥会用你 Mac 钥匙串中的密钥加密。模型只能看到名称。" },
      { title: "活动日志", body: "助理做过的每件事都保存在你的 Mac 上，并可撤销。" },
      { title: "由 Vunemi 创建", body: "它写的文件、保存的草稿、添加的日程和下载的文件，都可以“打开”或“在访达中显示”。" },
      { title: "发件箱", body: "等待发送的消息，以及每条消息的处理结果。" },
      { title: "应用锁", body: "用触控 ID 或 Mac 密码锁定 Vunemi。" },
      { title: "你的数据，你做主", body: "可以忘记单个会话、单条笔记或全部内容。记忆中的笔记永远不会授予权限，来自网页、邮件或文件的文字也永远不会成为笔记。" },
    ],
    extras: [
      { title: "在你的 Mac 上运行", body: "使用 Vunemi 内置引擎，或你已有的模型服务器：LM Studio、Ollama 或 llama.cpp。也可以添加 Mac 上的 GGUF 文件。" },
      { title: "11 种语言", body: "中文、英语、土耳其语、德语、法语、西班牙语、意大利语、葡萄牙语、俄语、日语和韩语。" },
    ],
  },
  screensPage: {
    title: "Vunemi 应用画面",
    intro: "英文版应用的真实画面，使用示例数据截取。点开任意图片可查看原尺寸。",
  },
  downloadPage: {
    highlightsTitle: "本次更新",
    highlights: [
      "语音对话：点麦克风旁边的波形按钮即可开启。Vunemi 会逐句朗读回答，你可以随时开口打断。它可以自行聆听，也可以只在你按下麦克风时聆听；房间里有其他人时请选择按下，因为你身边的声音可能被当成你的。",
      "会议可以区分通话中的人：人物 1、人物 2……由你为他们命名并更正错误。在你到“会议”中开启之前它保持关闭；需要一次性下载，并在你的 Mac 上运行。",
      "个性：在“设置 › 个性”中用你自己的话写下 Vunemi 应该怎样和你说话。它只改变语气和风格，不会改变 Vunemi 可以做什么。",
      "历史记录会在找到的每个会话或会议下方显示与你的请求相符的那句话，并在后台准备新的会话。",
      "网页表单中有更多字段被视为由你自己填写的个人信息：联系方式旁边的普通姓名或地址字段，以及电话号码。回答中直接写出的网址同样会标记为“未核实”。",
    ],
    title: "下载 Vunemi",
    intro: "免费且开源。适用于搭载 Apple 芯片、运行 macOS 14 或更高版本的 Mac。",
    requirementsTitle: "所需条件",
    requirements: ["搭载 Apple 芯片的 Mac（M1 或更新）", "macOS 14 或更高版本", "存放模型的空间：下载前应用会显示每个模型的大小"],
    installTitle: "安装",
    install: [
      "打开下载好的磁盘映像。",
      "把 Vunemi 拖到“应用程序”文件夹。",
      "从“应用程序”打开 Vunemi。如果 macOS 提示无法打开，请前往“系统设置 › 隐私与安全性”，点按“仍要打开”。",
      "在第一个画面选择模型。Vunemi 会推荐适合你 Mac 的模型。",
    ],
    updateTitle: "更新",
    updateBody: "从 0.1.8 起，新版本发布时 Vunemi 会通知你，点按“更新”即可自动更新。如果你使用的是更早的版本，请再下载一次新的磁盘映像，将 Vunemi 拖到“应用程序”并选择“替换”。",
    checksum: "SHA-256",
    notes: "版本说明",
    source: "源代码",
    guide: "指南",
  },
};
